### ISSUE TITLE
AWS::S3::Bucket-RequesterPays

### ISSUE THREAD

**Issue by bjorg** [aws-cloudformation/aws-cloudformation-coverage-roadmap#123]
## 1. Title 
AWS::S3::Bucket-RequesterPays

## 2. Scope of request 
Enable CloudFormation to set the [Requester Pays](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html) property on an S3 bucket. Currently, this property can only be set by the AWS console and AWS SDK.

## 3. Expected behavior
```yaml
MyBucket:
  Type: AWS::S3::Bucket
  Properties:
    RequestPayment:
      Payer: Requester
```

## 5. Helpful Links to speed up research and evaluation
* This feature was announced in Jun 2014, but is still not supported by CloudFormation. Announcement: https://aws.amazon.com/blogs/developer/amazon-s3-requester-pays/
* Requester Pays documentation: https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html
