### ISSUE TITLE
AWS::S3::Bucket-Rule-ExpiredObjectDeleteMarker

### ISSUE THREAD

**Issue by cccassidy** [aws-cloudformation/aws-cloudformation-coverage-roadmap#132]
## 2. Scope of request 
Add ExpiredObjectDeleteMarker option to S3 lifecycle policy specifications.

## 3. Expected behavior
Enable/Disable remove of expired object delete markers

```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteMarker
            Prefix: "/"
            Status: Enabled
            ExpiredObjectDeleteMarker: true
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Storage (S3, EFS, Backup...)
