### ISSUE TITLE
AWS::CertificateManager::Certificate DNS Validation Return Values

### ISSUE THREAD

**Issue by TheSkorm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#159]
New return value. When performing DNS Validation of certificate names it would be useful to have return values for the subdomain and value. Boto3 already returns this when requesting a new certificate : https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm.html#ACM.Client.request_certificate (look for ResourceRecord)
This is useful for providing either an Output for the stack or being referenced inside the stack it's self to create the record for DNS validation.

Example usage could be:
```
mycert:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: example.com
    DomainValidationOptions:
          - DomainName: example.com
            ValidationDomain: example.com
myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneResource'
      Name: !GetAtt mycert.DNSValidationName
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt mycert.DNSValidationValue
```
