### ISSUE TITLE
AWS::SQS::Queue-FifoQueue: support false

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#165]
1. Title ->AWS::SQS::Queue-FifoQueue
2. Scope of request -> AWS::SQS::Queue-FifoQueue is not a valid property when not creating a FIFO queue. It should be able to be present if it is set to false.
3. Expected behavior -> The template below should successfully create a regular SQS queue.
4. Test case recommendation -> The template below fails with error "Unknown Attribute FifoQueue".
5. Links to existing API doc: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html
6. Category tag -> Integration
7. Any additional context: see template below

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: false
```

**Comment by aravindparappil46** [comment]
Any update on this? This is a blocker for my team right now. Any viable workarounds/band-aids?

**Comment by BourgoisMickael** [comment]
> Any update on this? This is a blocker for my team right now. Any viable workarounds/band-aids?

```
Conditions:
  IsFifo: !Equals [!Ref FifoQueue, "true"]

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: !If [IsFifo, true, !Ref AWS::NoValue]
```
