### ISSUE TITLE
AWS::Cognito::ResourceServer

### ISSUE THREAD

**Issue by jacintoArias** [aws-cloudformation/aws-cloudformation-coverage-roadmap#173]
## 1. Scope of request

b) new resource type for an existing service is desired

API has support for creating, updating and removing resource servers as an individual entity on user pools.

## 2. Expected behavior

Template is quite straightforward from the API:

```yaml
MyResourceServer:
  Type: AWS::Cognito::ResourceServer
  Properties:
    UserPoolId: String
    Identifier: String
    Name: String
    Scopes:
      - CognitoResourceServerScope
```
CognitoResourceServerScope
```yaml
ScopeName: String
ScopeDescription: String
```

## 4. Suggest specific test cases

As commented, the Resource Server scopes are used when defining a User Pool Client, so testing the creation of both elements simoultaneously in a template should be mandatory.

```yaml
MyResourceServer:
  Type: AWS::Cognito::ResourceServer
  Properties:
    ...
    Name: myResourceServer
    Scopes:
      - ScopeName: scope_one
         ScopeDescription: My first scopre
      - ScopeName: scope_two
         ScopeDescription: My second scopre

UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
     ...
     AllowedOAuthFlowsUserPoolClient: true
     SupportedIdentityProviders: 
         - COGNITO
        AllowedOAuthFlows: 
          - code
        AllowedOAuthScopes:
          - openid
          - email
          - myResourceServer/scope_one
          - myResourceServer/scope_two
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

8. Security (IAM, KMS...)

## 7. Any additional context (optional)

Right now there is a __"bug"__ that prevents from creating a User Pool Client with the `client_credentials` OAuth flow activated (without using a custom resource).

Such clients cannot use the user base scopes (openid, profile, email...) in the `AllowedOAuthScopes` property, and it cannot be set as an empty string. As a result we can not define such type of clients without having available custom scopes, that can only be defined by ResourceServers.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-allowedoauthscopes
