### ISSUE TITLE
Breaking Change in AWS::GuardDuty::IPSet: Name wasn't required, but is now

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/aws-cloudformation-coverage-roadmap#1871]
### Name of the resource

AWS::GuardDuty::IPSet

### Issue Description

Previously (it's hard to say for how long, but at least until 2023-03-30 [according to the Wayback Machine](https://web.archive.org/web/20230330185059/https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-ipset.html#cfn-guardduty-ipset-name), the `Name` property in AWS::GuardDuty::IPSet was optional (Required: No). Currently that isn't the case anymore (Required: Yes). 

This makes it impossible to deploy existing templates to new stacks, or edit templates without adding the Name property

### Expected Behavior

Name should not be required

### Observed Behavior

Name is required

### Test Cases

I have this resource deployed in an existing stack:

```yaml
TrustedIpList:
  Type: AWS::GuardDuty::IPSet
  Properties:
    Activate: true
    DetectorId: !Ref Detector
    Format: TXT
    Location: !Sub https://s3.amazonaws.com/${ConfigBucket}/${TrustedIpListPath}
```
