### ISSUE TITLE
AWS::IAM::Role (add tagging support)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#19]
1. Title -> Customers would like to be able to tag IAM Roles from a CloudFormation template, after the recent introduction of the feature. Support for tags in IAM principals has been added to Boto 3 as well.
2. Scope of request -> Add at creation, and to update existing roles.
3. Expected behavior -> See 2.
4. Test case recommendation (optional) ->
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> Compute
7. Any additional context (optional)

**Comment by pbsinclair42** [comment]
Looks like this is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags

**Comment by whereisaaron** [comment]
https://github.com/weaveworks/eksctl/issues/778

**Comment by jimsmith** [comment]
Hello,

Having deployed CF template using the IAM Roles 'tags' https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags

I have found that the `!Ref` is not being honored.

This below works when it's hardcoded
```
Tags:
        - 
          Key: "keyname1"
          Value: "value1"
        - 
          Key: "keyname2"
          Value: "value2"
```

This below is not working and the same Parameter works for EC2 and Lambda resources.

```
Tags:
        - Key: Application
          Value: !Ref 'Application'
        - Key: Application
          Value: !Ref 'Application'
```
