### ISSUE TITLE
[AWS::Events::Rule] - [BUG] - EventBridge Rule drifted if using Dead Letter Queue (SQS DLQ)

### ISSUE THREAD

**Issue by FrcMoya** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2006]
### Name of the resource

AWS::Events::Rule

### Issue Description

CloudFormation still returns "drifted" when a Events::Rule has a DLQ. I created an issue #1605 that was resolved but in AWS I see this problem again.

### Expected Behavior

No drift in the EventBridge Rule

### Observed Behavior

EventBridge Rule drifted if it is using a DLQ

### Test Cases

Create a EventBridge Rule using Cloudformation with a target with a DLQ and check drift status of the stack

**Comment by woocy50** [comment]
2024-07-17
Verified the fix by deploying the following stack and checking for drift:
```
{
  "Resources": {
    "EventRule0": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "EventBusName": "default",
        "Name": "AROSRegionStateBackfillLa-fifteenMinuteRule4E348179-7wzKrSgXLpdx",
        "ScheduleExpression": "cron(0/15 * * * ? *)",
        "State": "ENABLED",
        "Targets": [
          {
            "Id": "Target0",
            "Arn": "arn:aws:lambda:us-east-2:339712857713:function:SampleFunction",
            "RetryPolicy": {
              "MaximumRetryAttempts": 0
            },
            "DeadLetterConfig": {
              "Arn": "arn:aws:sqs:us-east-2:339712857713:FifteenMinuteRuleDLQ"
            }
          }
        ]
      }
    }
  }
}
```

The drift check returned `IN_SYNC` for IAD, PDX, CMH, YYC, and SYD. Concluding the issue has been fully patched, therefore resolving the issue.

**Comment by aleklale-amazon** [comment]
Please, close this issue and re-open a new one if this issue is reoccuring.

**Comment by rgoltz** [comment]
> Please, close this issue and re-open a new one if this issue is reoccuring.

What is the benefit for this overhead / extra steps?

**Comment by aleklale-amazon** [comment]
Since this issue is old, the issue on GitHub may be open while there's no more issue to solve. I wanted to verify this was still occurring.

I can't reproduce this issue. Check out the steps below.

#### Test case and results

Template deployed (/tmp/dlq-drift-test.yaml):
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TargetQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: drift-test-target

  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: drift-test-dlq

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: drift-test-rule
      ScheduleExpression: "rate(1 hour)"
      State: ENABLED
      Targets:
        - Id: sqs-target
          Arn: !GetAtt TargetQueue.Arn
          DeadLetterConfig:
            Arn: !GetAtt DLQ.Arn
```


Commands executed:
```bash
# Deploy stack
aws cloudformation deploy --template-file /tmp/dlq-drift-test.yaml --stack-name dlq-drift-test --region us-east-1

# Check what EventBridge API returns
aws events list-targets-by-rule --rule drift-test-rule --region us-east-1
```


API Response:
```json
{
    "Targets": [
        {
            "Id": "sqs-target",
            "Arn": "arn:aws:sqs:us-east-1:<account-id>:drift-test-target",
            "DeadLetterConfig": {
                "Arn": "arn:aws:sqs:us-east-1:<account-id>:drift-test-dlq"
            }
        }
    ]
}
```


Drift detection:
```bash
aws cloudformation detect-stack-drift --stack-name dlq-drift-test --region us-east-1
aws cloudformation describe-stack-resource-drifts --stack-name dlq-drift-test --region us-east-1
```


Result: IN_SYNC - No drift detected

#### Next steps
If you're still experiencing this issue, please provide your test case in a similar format so we can reproduce it on our end and understand where the issue lies.
