### ISSUE TITLE
[AWS::ElastiCache::ReplicationGroup] - [BUG] - Missing default `aws::*` Tags

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2009]
### Name of the resource

AWS::ElastiCache::ReplicationGroup

### Issue Description

`AWS::ElastiCache::ReplicationGroup` is missing the default CloudFormation Tags like

    aws:cloudformation:logical-id
    aws:cloudformation:stack-id
    aws:cloudformation:stack-name

### Expected Behavior

Default Tags are added to the CloudFormation resources.

### Observed Behavior

Does not compute.

### Test Cases

```yaml
myReplicationGroup:
  Type: 'AWS::ElastiCache::ReplicationGroup'
  Properties:
    ReplicationGroupDescription: my description
    NumCacheClusters: '2'
    Engine: redis
    CacheNodeType: cache.m3.medium    
    AutomaticFailoverEnabled: 'true'
    CacheSubnetGroupName: subnetgroup
    EngineVersion: 2.8.6
    PreferredMaintenanceWindow: 'wed:09:25-wed:22:30'
    SnapshotRetentionLimit: '4'
    SnapshotWindow: '03:30-05:30'
```
