### ISSUE TITLE
[AWS::ElastiCache::ParameterGroup] - [BUG] - Missing default `aws::*` Tags

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2010]
### Name of the resource

AWS::ElastiCache::ParameterGroup

### Issue Description

`AWS::ElastiCache::ParameterGroup` is missing the default CloudFormation Tags like

    aws:cloudformation:logical-id
    aws:cloudformation:stack-id
    aws:cloudformation:stack-name

### Expected Behavior

Default Tags are added to the CloudFormation resources.

### Observed Behavior

Does not compute.

### Test Cases

```yaml
MyParameterGroup:
  Type: 'AWS::ElastiCache::ParameterGroup'
  Properties:
    Description: MyNewParameterGroup
    CacheParameterGroupFamily: memcached1.4
    Properties:
      cas_disabled: '1'
      chunk_size_growth_factor: '1.02'   
```
