### ISSUE TITLE
AWS::WorkSpacesWeb::UserSettings - CloudFormation unable to add AllowList for CookieSynchronizationConfiguration

### ISSUE THREAD

**Issue by jainakhi** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2011]
### Name of the resource

AWS::WorkSpacesWeb::UserSettings

### Description

CloudFormation unable to update the existing User Setting managed by CloudFormation with the 
`CookieSynchronizationConfiguration`.

When adding the below snippet, CloudFormation throws an error:

  ```
UserSettings:
    Type: AWS::WorkSpacesWeb::UserSettings
    Properties:
      CookieSynchronizationConfiguration:
        Allowlist:
          - Domain: .login.microsoftonline.com
      CopyAllowed: Enabled
      DownloadAllowed: Enabled
      PasteAllowed: Enabled
      PrintAllowed: Enabled
      UploadAllowed: Enabled
      DisconnectTimeoutInMinutes: 10
      IdleDisconnectTimeoutInMinutes: 5
```
**Error**
```
Resource handler returned message: "null" (RequestToken: 340dd58c-809a-ed40-6f31-e73c83b7a472, HandlerErrorCode: InternalFailure)
```

Additionally, the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-workspacesweb-usersettings-cookiespecification.html) mentions that it supports the `name` and `path` property. However, adding the same from CloudFormation also leads to the same error.

These properties seem to be contrary to the console and cli behaviour wherein, it **does not** allow to add these properties. Maybe the documentation should be updated to reflect the same behaviour as well.

### Other Details

https://docs.aws.amazon.com/cli/latest/reference/workspaces-web/update-user-settings.html
