### ISSUE TITLE
[AWS::ElastiCache::SubnetGroup] - [Coverage] - Stacklevel-Tags not propagated to Resource

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2031]
### Name of the resource

AWS::ElastiCache::SubnetGroup

### Description

For some unknown reason Stacklevel-Tags are not added to `AWS::ElastiCache::SubnetGroup`, even though `Tags` are supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-subnetgroup.html#cfn-elasticache-subnetgroup-tags

Example Stack:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Example

Resources:
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet Group for ElastiCache"
      SubnetIds:
        - <Subnet>
```

### Other Details

CloudFormation Drift Detection is finding this issue as a proper drift, since drift detection is expecting the stacklevel-tags on the resource.

**Comment by singhprz** [comment]
Hi,

We have validated that stack level tags are being propagated to subnet groups. To investigate further, could you please share your CloudFormation template as well as the method you're using to create the CloudFormation stack?

Thank you

**Comment by r-heimann** [comment]
Hi, thank you for your quick reply.

We are seeing this behavior in the AWS region `eu-central-1` using the following CloudFormation template:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Example

Resources:
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet Group for ElastiCache"
      SubnetIds:
        - <Subnet>
```

Using the CloudFormation GUI to add Stacklevel-Tags:

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/121236014/61e16e71-c90e-46fc-b3ad-47208162892c)

results in the Stacklevel-Tags not being added:

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/121236014/ece63f0a-7111-4735-bec1-043c0e6b53b3)

and CloudFormation Drift Detection finding this as a proper drift, since the tags are actually missing:

![Screenshot 2024-05-16 061832](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/121236014/3fa50b88-450e-4453-8c94-5cb99748c593)

I am currently unable to test this in any other region than `eu-central-1`, so it may work in different regions.
