### ISSUE TITLE
[AWS::RDS::DBParameterGroup] - [Coverage] - `postgres13` missing Drift Detection support for `Parameters`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2032]
### Name of the resource

AWS::RDS::DBParameterGroup

### Description

For some unknown reason CloudFormation Drift Detection is unable to verify the integrity of `Parameters` in a `postgres13` `AWS::RDS::DBParameterGroup`. Example:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Example

Resources:
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "Parameter Group"
      Family: postgres13
      Parameters:
        shared_preload_libraries: pg_stat_statements
```

this will cause a false-positive drift:

Property | Change | Expected value | Current value
-- | -- | -- | --
Parameters | REMOVE | {} | -
