### ISSUE TITLE
[AWS::DynamoDB::GlobalTable] - [Enhancement] - Implement console link to AWS Resource from "Resources" tab

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2067]
### Name of the resource

AWS::DynamoDB::GlobalTable

### Description

See https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/139, it is currently missing support for this feature.

### Other Details

(1) Deploy the following Test-Template:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN - create a new DynamoDB and CFN Console

Parameters:
  DBTableName: 
    Type: String
    Default: CfnTestPrices
    Description: Should be the table name to test
  PrimaryRegion: 
    Type: String
    Default: us-east-1
    Description: Region Primary Table is located

Resources:
  CfnTestPrices:
    Type: AWS::DynamoDB::GlobalTable
    DeletionPolicy: Retain
    Properties:
      TableName: !Ref DBTableName
      BillingMode: "PROVISIONED"
      AttributeDefinitions:
      - AttributeName: priceId
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: priceId
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      StreamSpecification:
            StreamViewType: "KEYS_ONLY"
      WriteProvisionedThroughputSettings:
        WriteCapacityAutoScalingSettings:
          MaxCapacity: 20 
          MinCapacity: 10
          TargetTrackingScalingPolicyConfiguration: 
            TargetValue: 70.0
            ScaleInCooldown: 61
            ScaleOutCooldown: 61
            DisableScaleIn: false
      Replicas:
       - 
        Region: !Ref PrimaryRegion
        DeletionProtectionEnabled: true
        ReadProvisionedThroughputSettings:
          ReadCapacityAutoScalingSettings:
            MaxCapacity: 20
            MinCapacity: 10 
            TargetTrackingScalingPolicyConfiguration:
              ScaleInCooldown: 50
              ScaleOutCooldown: 50
              TargetValue: 70.0
              DisableScaleIn: false
```

(2) Go to "Resources" tab in AWS Console of CloudFormation:
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/16392819/0d6a6017-a56b-4354-a5ab-1ff486f207b4)

You are not able to click on the "Physical ID" (which should link the service in the AWS Console). 
If you deploy a AWS::DynamoDB::Table, it's working. The Physical ID Link of a AWS::DynamoDB::Table resource is available/working.
