### ISSUE TITLE
AWS::IAM::VirtualMFADevice - Tags and Users not recognized by drift detection

### ISSUE THREAD

**Issue by fbzioui** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2087]
### Name of the resource

AWS::IAM::VirtualMFADevice

### Issue Description

When drift is detected for the **'AWS::IAM::VirtualMFADevice'** resource type, this results in a DRIFTED state even though there is no change to the resource and, depending on the drift results, the **'Tags'** and **'Users'** properties are not recognised by drift detection and are marked as removed although they exist.

### Expected Behavior

The resource should be in the **IN_SYNC** state when there is no change.

### Observed Behavior

The resource shows **MODIFIED** and the **'Tags'** and **'Users'** properties are marked as removed while they exist

### Test Cases

1- Create a resource type AWS::IAM::VirtualMFADevice with 'Tags' and 'Users' properties:

```
Resources:
  TestDrift:
    Type: AWS::IAM::VirtualMFADevice
    Properties:
      Tags:
        - Key: Test
          Value: drift
      Users:
        - test
      VirtualMfaDeviceName: DriftTest
```
2- Perform Drift Detection operation
3- The drift results will show the resource as DRIFTED while there is no change.
