### ISSUE TITLE
[AWS::AccessAnalyzer::Analyzer] - [BUG] - Stack-Level Tags are not propagated to the resource

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2110]
### Name of the resource

AWS::AccessAnalyzer::Analyzer

### Issue Description

Stack-Level Tags are not added to `AWS::AccessAnalyzer::Analyzer`.

### Expected Behavior

Stack-Level Tags are added to `AWS::AccessAnalyzer::Analyzer`.

### Observed Behavior

Stack-Level Tags are not added to `AWS::AccessAnalyzer::Analyzer`.

### Test Cases

Create a CloudFormation Stack with Stack-Level Tags:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  AccessAnalyzer:
    Type: AWS::AccessAnalyzer::Analyzer
    Properties:
      Type: ACCOUNT
```
