### ISSUE TITLE
[AWS::AccessAnalyzer::Analyzer] - [BUG] - Missing default `aws::*` Tags

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2111]
### Name of the resource

AWS::AccessAnalyzer::Analyzer

### Issue Description

`AWS::AccessAnalyzer::Analyzer` is missing the default CloudFormation Tags like

```
aws:cloudformation:logical-id
aws:cloudformation:stack-id
aws:cloudformation:stack-name
```

### Expected Behavior

Tags are added.

### Observed Behavior

Tags are not added.

### Test Cases

Create a CloudFormation Stack and check the Tags of the Analyzer:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Test

Resources:
  AccessAnalyzer:
    Type: AWS::AccessAnalyzer::Analyzer
    Properties:
      Type: ACCOUNT
```
