### ISSUE TITLE
AWS::EKS::AccessEntry - The EKS AccessEntry "STANDARD" Type Naming Correction

### ISSUE THREAD

**Issue by patel0ankur** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2116]
### Name of the resource

AWS::EKS::AccessEntry

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-accessentry.html#cfn-eks-accessentry-type:~:text=%3A%20No%20interruption-,Type,-The%20type%20of

### Details

The AWS::EKS::AccessEntry CloudFormation resource type contains a typographical error in the documentation for the "[Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-accessentry.html#cfn-eks-accessentry-type:~:text=%3A%20No%20interruption-,Type,-The%20type%20of)" property, where "**Standard**" is incorrectly spelled instead of the correct uppercase "**STANDARD**".

The Document says the valid values are **Standard**, FARGATE_LINUX, EC2_LINUX, and EC2_WINDOWS.

The correct value should be **STANDARD** instead of **Standard**.

CloudFormation Code using **Type** as **Standard**:
```
Resources:
  MyAccessEntry:
    Type: 'AWS::EKS::AccessEntry'
    Properties:
      ClusterName: 'eks-workshop'
      PrincipalArn: 'arn:aws:iam::xxxxxxxx:role/appsync-role'
      Username: 'appsync'
      AccessPolicies:
        - PolicyArn: 'arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminPolicy'
          AccessScope:
            Type: 'namespace'
            Namespaces:
              - 'carts'
      Type: 'Standard'
```

Received Error in the Events:

```
Resource handler returned message: "AccessEntry type must be one of [EC2_LINUX, EC2_WINDOWS, FARGATE_LINUX, STANDARD] (Service: Eks, Status Code: 400, Request ID: cabe563e-3eb2-45cd-9b53-8ea109e11ff9)" (RequestToken: 354a18ad-b9ab-26a7-3133-8da180bc10f7, HandlerErrorCode: InvalidRequest)
```

Please correct the spelling from **Standard** to **STANDARD** in the AWS document.
