### ISSUE TITLE
[AWS::ElasticLoadBalancingV2::Listener ] - [Coverage] - Support Listener Attribute

### ISSUE THREAD

**Issue by mazyu36** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2121]
### Name of the resource

AWS::ElasticLoadBalancingV2::Listener

### Description

Network Load Balancer now supports TCP idle timeout (Ref: [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/09/aws-network-load-balancer-tcp-idle-timeout/)).

To use this, we need to set `tcp.idle_timeout.seconds` to the listener attributes. 
However, listener attributes cannot be configured in the current CloudFormation.

In the case of CLI, it can be set using the following command:

```sh
aws elbv2 modify-listener-attributes \
          --listener-arn arn:aws:elasticloadbalancing:us-east-1:000011112222:listener/network/NLBTest/123/123 \
          --attributes \
              Key=tcp.idle_timeout.seconds,Value=600 
```

Ref: https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-nlb-tcp-configurable-idle-timeout/

**Comment by andreybutenko** [comment]
Hi from the Elastic Load Balancing team! Our team is actively working on adding listener attributes support to our Cloudformation handler. We will share additional details soon.

**Comment by andreybutenko** [comment]
Hi from the Elastic Load Balancing team!

Our team has completed implementation for listener attributes support in our Cloudformation handler.

We are now preparing to deploy the feature to all regions. We tentatively estimate that it will take ~2 weeks to deploy the feature to all regions. Once the feature is deployed to all regions, customers will be able to manage their listener attributes through Cloudformation

We will continue to update this issue as we have updates!

**Comment by wweiwei-li** [comment]
Update: Listener attributes support in Cloudformation handler is available in all commercial regions and Gov clouds.

**Comment by jsnappzelis** [comment]
Does this also apply for Gateway Load Balancers?

**Comment by mazyu36** [comment]
@andreybutenko 
Thank you for your assistance!
I tried to set the TCP Idle timeout using CloudFormation, but I encountered the following error and couldn't configure it.

>Resource handler returned message: "The security token included in the request is invalid (Service: ElasticLoadBalancingV2, Status Code: 403, 

Is this feature not supported yet?

```yaml
    "LBListener49E825B4": {
      "Type": "AWS::ElasticLoadBalancingV2::Listener",
      "Properties": {
        "DefaultActions": [
          {
            "TargetGroupArn": {
              "Ref": "LBListenerTargetGroupF04FCF6D"
            },
            "Type": "forward"
          }
        ],
        "ListenerAttributes": [
          {
            "Key": "tcp.idle_timeout.seconds",
            "Value": "100"
          }
        ],
        "LoadBalancerArn": {
          "Ref": "LB8A12904C"
        },
        "Port": 80,
        "Protocol": "TCP"
      }
    },
```
