### ISSUE TITLE
[AWS::SES::ConfigurationSetEventDestination] - [BUG] - Updating EventDestination.Name makes no changes

### ISSUE THREAD

**Issue by cyounkins** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2131]
### Name of the resource

AWS::SES::ConfigurationSetEventDestination

### Issue Description

Updating the EventDestination.Name property does not change

### Expected Behavior

I expected the update to be rejected, the event destination to be modified, or to be re-created

### Observed Behavior

No changes

### Test Cases

```
  CloudwatchEvents:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref SESConfigurationSet
      EventDestination:
        Name: !Sub ${SESConfigurationSet}-cloudwatch
        Enabled: true
        MatchingEventTypes:
          - send
          - reject
          - bounce
          - complaint
          - delivery
          - renderingFailure
          - deliveryDelay
          - subscription
        CloudWatchDestination:
          DimensionConfigurations:
            - DimensionName: ses:configuration-set
              DimensionValueSource: messageTag
              DefaultDimensionValue: default
```

Change Name to `!Sub ${SESConfigurationSet}-cloudwatch2` and update. Observe no changes in console.
