### ISSUE TITLE
AWS::RDS::DBInstance - Replica to support Multi AZ

### ISSUE THREAD

**Issue by fredc0088** [aws-cloudformation/aws-cloudformation-coverage-roadmap#215]
## 2. Scope of request 
Cloudformation for read replica databases should accept multizone availability property and apply the new configuration, as [replicas already support multi az deployment](https://aws.amazon.com/about-aws/whats-new/2018/01/amazon-rds-read-replicas-now-support-multi-az-deployments/)

Sample: 
```yaml
RDSReadOnlyReplica:
          Type: "AWS::RDS::DBInstance"
          Properties:
            SourceDBInstanceIdentifier:
              Ref: "RDS"
            DBInstanceIdentifier: <identifier>
            DBParameterGroupName:
              Ref: "RDSReadReplicaDBParameterGroup"
            AllocatedStorage: "1000"
            StorageType: "gp2"
            DBInstanceClass: "db.r3.large"
            Engine: "postgres"
            MultiAZ: "True" // (or true)
            VPCSecurityGroups:
              - Ref: "RDSSecurityGroup"
```

## 3. Expected behavior
Deploy with a stack as above, should let the replica db change to multi az.
Feel free to describe other desired and relevant implementation details. 

## 4. Category (required) - Will help with tagging and be easier to find by other users to +1
DB (RDS)
Storage (RDS)
