### ISSUE TITLE
AWS::ECS::Service - PlacementConstraints: [] (empty array) results in false-positive drift

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2153]
### Name of the resource

AWS::ECS::Service

### Issue Description

Within your `AWS::ECS::Service` you are able to define a [PlacementConstraints](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-placementconstraints), which is a object/array of [PlacementConstraint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-placementconstraint.html).

In some case, it's needed to define this `PlacementConstraints` array as empty `[]`. Once you deploy such a configuration via CFN, it's resulting in a drift after running CloudFormation Drift Detection on those stacks.

### Expected Behavior

CloudFormation is aware of the possibility to define a empty array of PlacementConstraints - It's not resulting in a stack drift for AWS::ECS::Service.

### Observed Behavior

We are using CDK to generate our CFN templates. In CDK it's possible to define an empty array for PlacementConstraints: https://github.com/aws/aws-cdk/pull/30382. This was discussed here: https://github.com/aws/aws-cdk/issues/27555

After you deploy your stack (+ run CloudFormation Drift Detection), you will see following drift details for AWS::ECS::Service:
![PlacementCon-DriftDetail](https://github.com/user-attachments/assets/cd8c41cd-2e79-4781-acff-e1e16e46e066)
(It's missing on "Expected")

### Test Cases

(Please mind that you need to create a Cluster, TaskDefinition, ... before you are able deploy a a ECS Service. Please mind the **PlacementConstraints** CFN definition)

```yaml
  ECSServiceByCDK:
    Type: AWS::ECS::Service
    Properties:
      CapacityProviderStrategy:
        - CapacityProvider:
            Fn::ImportValue: YourCapProviderReferenceInOtherStack
          Weight: 1
      Cluster: rogoECS-sandbox-Cluster
      DeploymentConfiguration:
        Alarms:
          AlarmNames: []
          Enable: false
          Rollback: false
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: false
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: false
      HealthCheckGracePeriodSeconds: 120
      LoadBalancers:
        - ContainerName: sidecar
          ContainerPort: 10000
          TargetGroupArn:
            Fn::ImportValue: YourTargetGroupReferenceInOtherStack
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: YourSecGroupReferenceInOtherStack
          Subnets:
            - subnet-001
            - subnet-002
            - subnet-003
      PlacementConstraints: []
      PlacementStrategies:
        - Field: attribute:ecs.availability-zone
          Type: spread
        - Field: CPU
          Type: binpack
      SchedulingStrategy: REPLICA
      ServiceName: ecs-Service-sandbox1-drift-rogo
      Tags:
        - Key: AwsCaseForThisIssue
          Value: 172796075700011
      TaskDefinition:
        Ref: ECSTaskDefinitionByCDK
```

### Other Details

The deployed ECS Service Looks like this (for Task placement constraint):
![PlacementCon-ResourceDetail](https://github.com/user-attachments/assets/6c139b22-0f49-4ce9-b595-727dcc018cfb)

**Comment by greg5123334** [comment]
Confirmed.

## Replication
### Control
``` typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as ecs from "aws-cdk-lib/aws-ecs";
import * as autoscaling from "aws-cdk-lib/aws-autoscaling";

export interface SandboxProps extends cdk.StackProps {
  vpc: ec2.IVpc;
}

export class SandboxStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: SandboxProps) {
    super(scope, id, props);

    let vpc = props.vpc;

    // Create an ECS cluster
    const cluster = new ecs.Cluster(this, "MyCluster", {
      vpc: vpc,
    });

    const autoScalingGroup = new autoscaling.AutoScalingGroup(this, "ASG", {
      vpc,
      instanceType: new ec2.InstanceType("t3.micro"),
      machineImage: ecs.EcsOptimizedImage.amazonLinux2023(),
      desiredCapacity: 3,
    });
    const capacityProvider = new ecs.AsgCapacityProvider(
      this,
      "AsgCapacityProvider",
      {
        autoScalingGroup,
      }
    );
    cluster.addAsgCapacityProvider(capacityProvider);

    // Create a task definition
    const taskDefinition = new ecs.Ec2TaskDefinition(this, "MyTaskDefinition");

    // Add a container to the task definition
    taskDefinition.addContainer("MyContainer", {
      image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      memoryLimitMiB: 256,
    });

    // Create an ECS service
    const ecsService = new ecs.Ec2Service(this, "MyEcsService", {
      cluster: cluster,
      taskDefinition: taskDefinition,
      desiredCount: 2,
      placementConstraints: [
        ecs.PlacementConstraint.memberOf("attribute:ecs.instance-type =~ t3.*"),
        ecs.PlacementConstraint.distinctInstances(),
      ],
    });
  }
}

```
``` yaml
  MyEcsService864C18BF:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: MyCluster4C1BA579
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: 2
      EnableECSManagedTags: false
      LaunchType: EC2
      PlacementConstraints:
        - Expression: attribute:ecs.instance-type =~ t3.*
          Type: memberOf
        - Type: distinctInstance
      SchedulingStrategy: REPLICA
      TaskDefinition:
        Ref: MyTaskDefinitionF5B350B4
    DependsOn:
      - MyTaskDefinitionTaskRole93FBB305
    Metadata:
      aws:cdk:path: SandboxStack/MyEcsService/Service
```

``` bash
aws cloudformation detect-stack-drift --stack-name SandboxStack --output json | jq .
```
``` json
{
  "StackDriftDetectionId": "8230af90-83b6-11ef-924c-0a75972cb829"
}
```
```bash
aws cloudformation describe-stack-drift-detection-status --stack-drift-detection-id 8230af90-83b6-11ef-924c-0a75972cb829 --output json | jq .
```
``` json
{
  "StackId": "arn:aws:cloudformation:eu-west-1:000000000000:stack/SandboxStack/4a50f920-83b3-11ef-9429-0a740903966f",
  "StackDriftDetectionId": "8230af90-83b6-11ef-924c-0a75972cb829",
  "StackDriftStatus": "IN_SYNC",
  "DetectionStatus": "DETECTION_COMPLETE",
  "DriftedStackResourceCount": 0,
  "Timestamp": "2024-10-06T07:42:16.329000+00:00"
}
```

**Result: IN_SYNC**
<img src="https://github.com/user-attachments/assets/73a3c736-29ad-492f-a633-18b5887cc39a" width="200" />

### Experiment

``` typescript
    // Create an ECS service
    const ecsService = new ecs.Ec2Service(this, "MyEcsService", {
      cluster: cluster,
      taskDefinition: taskDefinition,
      desiredCount: 2,
      placementConstraints: [], // <--------
    });
```
``` yaml
  MyEcsService864C18BF:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: MyCluster4C1BA579
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: 2
      EnableECSManagedTags: false
      LaunchType: EC2
      PlacementConstraints: []
      SchedulingStrategy: REPLICA
      TaskDefinition:
        Ref: MyTaskDefinitionF5B350B4
    DependsOn:
      - MyTaskDefinitionTaskRole93FBB305
    Metadata:
      aws:cdk:path: SandboxStack/MyEcsService/Service
```
``` bash
aws cloudformation detect-stack-drift --stack-name SandboxStack --output json | jq .
```
``` json
{
  "StackDriftDetectionId": "7313b560-83b7-11ef-8e60-0ac7a993af81"
}
```
```bash
aws cloudformation describe-stack-drift-detection-status --stack-drift-detection-id 7313b560-83b7-11ef-8e60-0ac7a993af81 --output json | jq .
```
``` json
{
  "StackId": "arn:aws:cloudformation:eu-west-1:000000000000:stack/SandboxStack/4a50f920-83b3-11ef-9429-0a740903966f",
  "StackDriftDetectionId": "7313b560-83b7-11ef-8e60-0ac7a993af81",
  "StackDriftStatus": "DRIFTED",
  "DetectionStatus": "DETECTION_COMPLETE",
  "DriftedStackResourceCount": 1,
  "Timestamp": "2024-10-06T07:49:00.470000+00:00"
}
```

**Result: DRIFTED**

``` bash
aws cloudformation describe-stack-resource-drifts --stack-name SandboxStack --output json --stack-resource-drift-status-filters MODIFIED DELETED | jq .
```
``` json
{
  "StackResourceDrifts": [
    {
      "StackId": "arn:aws:cloudformation:eu-west-1:000000000000:stack/SandboxStack/4a50f920-83b3-11ef-9429-0a740903966f",
      "LogicalResourceId": "MyEcsService864C18BF",
      "PhysicalResourceId": "arn:aws:ecs:eu-west-1:000000000000:service/SandboxStack-MyCluster4C1BA579-mVT8exG0oONu/SandboxStack-MyEcsService864C18BF-44UCBal90vpC",
      "ResourceType": "AWS::ECS::Service",
      "ExpectedProperties": "{\"SchedulingStrategy\":\"REPLICA\",\"TaskDefinition\":\"arn:aws:ecs:eu-west-1:000000000000:task-definition/SandboxStackMyTaskDefinition8F97A5F8:1\",\"EnableECSManagedTags\":false,\"PlacementConstraints\":[],\"Cluster\":\"SandboxStack-MyCluster4C1BA579-mVT8exG0oONu\",\"DesiredCount\":2,\"DeploymentConfiguration\":{\"MaximumPercent\":200,\"MinimumHealthyPercent\":50},\"LaunchType\":\"EC2\"}",
      "ActualProperties": "{\"SchedulingStrategy\":\"REPLICA\",\"TaskDefinition\":\"arn:aws:ecs:eu-west-1:000000000000:task-definition/SandboxStackMyTaskDefinition8F97A5F8:1\",\"EnableECSManagedTags\":false,\"Cluster\":\"SandboxStack-MyCluster4C1BA579-mVT8exG0oONu\",\"DesiredCount\":2,\"LaunchType\":\"EC2\",\"DeploymentConfiguration\":{\"MaximumPercent\":200,\"MinimumHealthyPercent\":50}}",
      "PropertyDifferences": [
        {
          "PropertyPath": "/PlacementConstraints",
          "ExpectedValue": "[]",
          "ActualValue": "null",
          "DifferenceType": "REMOVE"
        }
      ],
      "StackResourceDriftStatus": "MODIFIED",
      "Timestamp": "2024-10-06T07:49:04.610000+00:00"
    }
  ]
}
```
