### ISSUE TITLE
AWS CloudFormation Intrinsic Functions - Fn::ImportValue - Error

### ISSUE THREAD

**Issue by samriddhadev** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2168]
### Resource Name

When using Fn::ImportValue function, within Fn::Sub, observing the following weird behavior:

When following considered as valid:
![image](https://github.com/user-attachments/assets/ad6889cf-9dd8-44b5-9ae1-2ffa6777ae45)

However, following is NOT considered as valid cloudformation template:
![image](https://github.com/user-attachments/assets/6838d8ab-f639-4308-b9cd-0cee8bd449c5)

However, both are pointing to SAME cross stack reference.
 

### Details

When using Fn::ImportValue function, within Fn::Sub, observing the following weird behavior:

When following considered as valid:
![image](https://github.com/user-attachments/assets/ad6889cf-9dd8-44b5-9ae1-2ffa6777ae45)

However, following is NOT considered as valid cloudformation template:
![image](https://github.com/user-attachments/assets/6838d8ab-f639-4308-b9cd-0cee8bd449c5)

However, both are pointing to SAME cross stack reference.

**Comment by kddejong** [comment]
The structure for your Fn::Sub is a little off.  The second value in an Fn::Sub is an object with key and values.  So the following is how it should be structured.

```yaml
Parameters:
  Env:
    Type: String
    AllowedValues:
      - prod
      - stage
      - dev 
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: {}
      RoleName: !Sub
        - ${UAI}-${TEST}
        - UAI:
            Fn::ImportValue: !Sub "AeGAIUAI-${Env}"
          TEST:
            Fn::ImportValue: !Sub "AeGAIUAI-${Env}"
```

Unless I'm missing something I'm going to close this issue as I believe it is working as intended.  I can always reopen based on your feedback.
