### ISSUE TITLE
[AWS::Events::EventBus] - [BUG] - Policy not recognized by drift detection

### ISSUE THREAD

**Issue by fbzioui** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2188]
### Name of the resource

AWS::Events::EventBus

### Issue Description

When running drift detection on an AWS::Events::EventBus resource, the Policy applied to the ‘’actual‘’ configuration should be taken into consideration by drift detection.
Currently, the Policy is not correctly taken by the drift detection, resulting in what appears to be a false-positive drift.

### Expected Behavior

The resource should be in the IN_SYNC state when there is no change.

### Observed Behavior

The resource shows MODIFIED and the 'Policy' property is marked as removed while it exists

### Test Cases

1- Create a resource type AWS::Events::EventBus with 'Policy' property:

```
  SampleCustomEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: "MyCustomEventBus"
        Policy:
          Version: '2012-10-17'
          Statement:
            Sid: Test
            Effect: Allow
            Principal:
              AWS: 'AWS'
            Action: events:PutEvents
            Resource: 'RESOURCE'
```
2- Perform Drift Detection operation
3- The drift results will show the resource as DRIFTED while there is no change.

**Comment by rgoltz** [comment]
I ran into the same issue/bug - Here are my test-case and result:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Minimal repro for EventBus Policy drift false positive (#2188)"

Resources:
  TestEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: drift-bug-2188-test
      Policy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPutEvents
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: events:PutEvents
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/drift-bug-2188-test"
```

Here is the wrong result from Drift Detection:
<img width="1318" height="753" alt="Image" src="https://github.com/user-attachments/assets/e9400132-2063-4523-8e7e-a0cbd99e2bb8" />

**Comment by rgoltz** [comment]
I re-tested this issue in region us-east-1 using a minimal, self-contained template that reproduces the exact scenario from the original report (an `AWS::Events::EventBus` with an inline `Policy`).

Drift detection now reports the stack and the EventBus resource as **`IN_SYNC`**. The `Policy` property is no longer falsely flagged as removed and the false-positive drift is gone.

````yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Minimal repro for EventBus Policy drift false positive (#2188)"

Resources:
 TestEventBus:
   Type: AWS::Events::EventBus
   Properties:
     Name: drift-bug-2188-test
     Policy:
       Version: "2012-10-17"
       Statement:
          - Sid: AllowPutEvents
           Effect: Allow
           Principal:
             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
           Action: events:PutEvents
           Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/drift-bug-2188-test"
````

It's fixed now:
<img width="1646" height="723" alt="Drift Details for SYNC state" src="https://github.com/user-attachments/assets/a0391a00-535d-44be-a4b0-d8da303c9f82" />

@fbzioui - It's fine on your end now as well? Could you please confirm and close the issue? 

Thanks a lot for the fix CFN-Team!
