### ISSUE TITLE
[AWS::LakeFormation::DataLakeSettings] - [BUG] - Can not clear permissions

### ISSUE THREAD

**Issue by rehanvdm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2197]
### Name of the resource

AWS::LakeFormation::DataLakeSettings

### Issue Description

The `CreateDatabaseDefaultPermissions` and `CreateTableDefaultPermissions` properties does not clear the values, it is as if it does a no-op. The [docs state](https://docs.aws.amazon.com/lake-formation/latest/dg/change-settings.html) that empty arrays OR omitting the properties will clear the boolean fields on the UI, but it does not, it is just ignored. So these properties can not be unset after they have been set.

```
LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
      CreateDatabaseDefaultPermissions: []
      CreateTableDefaultPermissions: []
```

![image](https://github.com/user-attachments/assets/f2690292-f452-48e5-adf3-7d3d22be9cf3)

### Expected Behavior

The empty array or omitting the property should actually work

### Observed Behavior

The values can not be unset

### Test Cases

1. Deploy with 
```
LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
      CreateDatabaseDefaultPermissions:
        - Permissions:
            - ALL
          Principal:
            DataLakePrincipalIdentifier: IAM_ALLOWED_PRINCIPALS
      CreateTableDefaultPermissions:
        - Permissions:
            - ALL
          Principal:
            DataLakePrincipalIdentifier: IAM_ALLOWED_PRINCIPALS
```
2. Then remove them, observe the values have not changed via the AWS Console or API
```
LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
```
3. Attempt number two, set them as empty arrays, observe the values have not changed via the AWS Console or API
```
LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
      CreateDatabaseDefaultPermissions: []
      CreateTableDefaultPermissions: []
```
