### ISSUE TITLE
[AWS::Bedrock::Agent] - [Coverage] - Multiple Missing Features

### ISSUE THREAD

**Issue by aws-rafams** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2207]
### Name of the resource

AWS::Bedrock::Agent

### Description

Raising this issue for missing features already available through the AWS Console
- [x] [Memory](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-configure-memory.html) (allows an agent to retain conversational contexts across multiple sessions and recall past actions and behaviors)
- [x] [Multi-agent collaboration](https://aws.amazon.com/blogs/aws/introducing-multi-agent-collaboration-capability-for-amazon-bedrock/) (allows this agent to delegate tasks to collaborator agent)
- [ ] [Default Prompt Routers Support ](https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-routing.html)
- [x] [Custom Orchestration](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-custom-orchestration.html)

**Comment by mccauleyp** [comment]
Is there a timeline yet for including these features? I'm expecting them to be available somewhat soon given the enthusiasm for AI agents, so I'm wondering if I should build my own custom resources to use the missing features in an IaC context or if I should tell my stakeholders that we could spend that dev time elsewhere and wait a few more weeks for this coverage to improve.

**Comment by dave-moser** [comment]
+1

I noticed you can now create a REDSHIFT based Knowledgebase with CloudFormation and the CDK using the **sqlKnowledgeBaseConfiguration** option.

The subsequent **CfnDataSource** construct that is required to connect the data source (Redshift database) to the KnowledgeBase throws an error.

Cloudformatation Resource

```
  BedrockKnowledgeBaseRedshiftDataSource8560E802:
    Type: AWS::Bedrock::DataSource
    Properties:
      DataSourceConfiguration:
        Type: REDSHIFT_METADATA
      KnowledgeBaseId:
        Fn::GetAtt:
          - BedrockKnowledgeBaseRedshift97A91010
          - KnowledgeBaseId
      Name: kb-ds
```

Error

`Resource handler returned message: "1 validation error detected: Value null at 'dataSourceConfiguration' failed to satisfy constraint: Member must not be null`

It looks like CF is expecting the DataSourceConfiguration to have a sub-section definition, like other data source types have. Redshift, however, does not require any other details, only the "Type".

FWIW - this does work in the AWS Api (Boto3). For now, I am using a CDK custom resource to create the knowledgebase.
