### ISSUE TITLE
[AWS::Lambda::Function] - [Enhancement] - Support ImageUri as an attribute

### ISSUE THREAD

**Issue by packplusplus** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2211]
### Name of the resource

AWS::Lambda::Function

### Description

The [return values](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#aws-resource-lambda-function-return-values) are limited to the following:
- `SnapStartResponse`
- `SnapStartResponse.ApplyOn`
- `SnapStartResponse.OptimizationStatus`
- `Arn`

In the use case of a Sam Template, if you do an `AWS::Serverless::Function`, it does an `AWS::Lambda::Function` under the covers. If you are using an image_function, each function builds an independent Container Image. If `AWS::Lambda::Function` allowed you to get the ImageUri, you could have a single function build the image, and additional functions refer back to the initial image, reducing build times. 

Example:
```
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: funcCode
      ImageConfig:
        Command:
          - "app.lambda_handler1"
    Metadata:
      Dockerfile: funcCode/Dockerfile
      DockerTag: Function1
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: !GetAtt Function1.ImageUri
      ImageConfig:
        Command:
          - "app.lambda_handler2"
  Function3:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: !GetAtt Function1.ImageUri
      ImageConfig:
        Command:
          - "app.lambda_handler3"
```
