### ISSUE TITLE
AWS::CloudFormation::StackSet - return instance Outputs

### ISSUE THREAD

**Issue by mo7ty** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2216]
### Name of the resource

AWS::CloudFormation::StackSet

### Description

It would be a great help for the AWS community using CloudFormation templates for IaC to have [AWS::CloudFormation::StackSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html) returning [not just its logical ID](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#aws-resource-cloudformation-stackset-return-values), but also be <ins>**able to return its instance Outputs**</ins>.

Usage template sample:

```yaml
WAFStackSet:
  Type: AWS::CloudFormation::StackSet
  Properties:
    StackSetName: WAFStackSet
    Description: CloudFormation StackSet used to provision WAF resources
    PermissionModel: SELF_MANAGED
    StackInstancesGroup:
      - DeploymentTargets:
          Accounts: [!Ref "AWS::AccountId"]
        Regions: [us-east-1]
    TemplateBody: |
      AWSTemplateFormatVersion: 2010-09-09
      Description: WAF Stack
      Resources:
        WebACL:
          Type: AWS::WAFv2::WebACL
          Properties:
          ...
      Outputs:
        WAFWebACLId:
          Value: !GetAtt WebACL.Id

CloudFrontDistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      WebACLId: !GetAtt WAFStackSet.Outputs.WAFWebACLId
      ...

```

With this improvement being a solution to overcome limitations like:
* #523
* #546

Because there are also missing:
* #562
* #630

Additional references from re:Post that would benefit with this:
* [How to access StackSet instances outputs | AWS re:Post](https://repost.aws/questions/QUSAhSA2u6TraXHxzAH6GzLg/how-to-access-stackset-instances-outputs)
* [Reference cross-instance StackSet outputs | AWS re:Post](https://repost.aws/questions/QU52Z-JTP4QJq5zJstxwVA5g/reference-cross-instance-stackset-outputs)
