### ISSUE TITLE
AWS::CloudFront::AnycastIpList - [BUG] - Invalid request provided

### ISSUE THREAD

**Issue by t0yv0** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2222]
### Name of the resource

Other

### Resource Name

AWS::CloudFront::AnycastIpList

### Issue Description

Failing to provision an AWS::CloudFront::AnycastIpList resource with InvalidRequest without a helpful diagnostic message explaining what is unexpected with my configuration.

### Expected Behavior

AWS::CloudFront::AnycastIpList provisions or gracefully fails explaining what is wrong with the configuration.

### Observed Behavior

```
        {
            "StackId": "arn:aws:cloudformation:us-west-2:616138583583:stack/anton-test-anycastiplist-2-b/9fa0fac0-c480-11ef-bae1-0ae2e4a91c7f",
            "EventId": "AnycastIpList-CREATE_FAILED-2024-12-27T18:30:21.422Z",
            "StackName": "anton-test-anycastiplist-2-b",
            "LogicalResourceId": "AnycastIpList",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::CloudFront::AnycastIpList",
            "Timestamp": "2024-12-27T18:30:21.422000+00:00",
            "ResourceStatus": "CREATE_FAILED",
            "ResourceStatusReason": "Resource handler returned message: \"Invalid request provided: AWS::CloudFront::AnycastIpList\" (RequestToken: d2f6e4dd-da9d-cb23-4e87-5dbb44bab39b, HandlerErrorCode: InvalidRequest)",
            "ResourceProperties": "{\"IpCount\":\"1\",\"Name\":\"MyAnycastIpList\"}"
        },

```

### Test Cases

Using this CloudFormation template:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AnycastIpList

Resources:
  AnycastIpList:
    Type: AWS::CloudFront::AnycastIpList
    Properties:
      Name: MyAnycastIpList
      IpCount: 1

Outputs:
  AnycastIpListId:
    Description: The ID of the Anycast IP List
    Value: !Ref AnycastIpList

```
