### ISSUE TITLE
[AWS::Location::APIKey] - [Docs] - add Enhanced API Actions and Resources to ApiKeyRestrictions

### ISSUE THREAD

**Issue by mazyu36** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2225]
### Name of the resource

AWS::Location::APIKey

### Reference Link

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-location-apikey-apikeyrestrictions.html#cfn-location-apikey-apikeyrestrictions-allowactions

### Details

Amazon Location Service launches Enhanced Places, Routes, and Maps. [Ref](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-location-service-enhanced-places-routes-maps/?nc1=h_ls)

However, in the API Key CloudFormation documentation, the descriptions of `AllowActions` and `AllowResources` only cover legacy APIs, not enhanced APIs.
The documentation should include information about Enhanced APIs.

Ref
* https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonlocationservicemaps.html
* https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonlocationserviceplaces.html
* https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonlocationserviceroutes.html

I successfully deployed an API Key with Enhanced APIs Actions and Resources.
Therefore, this appears to be solely a documentation issue.

```yaml
  APIKey:
    Type: AWS::Location::APIKey
    Properties:
      Description: my api key for test
      ExpireTime: '2026-01-01T00:00:00.000Z'
      KeyName: my-api-key
      NoExpiry: false
      Restrictions:
        AllowActions:
          - geo-maps:GetStaticMap
          - geo-maps:GetTile
          - geo-places:Autocomplete
          - geo-places:Geocode
          - geo-places:GetPlace
          - geo-places:ReverseGeocode
          - geo-places:SearchNearby
          - geo-places:SearchText
          - geo-places:Suggest
          - geo-routes:CalculateIsolines
          - geo-routes:CalculateRoutes
          - geo-routes:CalculateRouteMatrix
          - geo-routes:OptimizeWaypoints
          - geo-routes:SnapToRoads
        AllowReferers:
          - https://example.com
        AllowResources:
          - arn:aws:geo-maps:us-east-1::provider/default
          - arn:aws:geo-places:us-east-1::provider/default
          - arn:aws:geo-routes:us-east-1::provider/default
```
