### ISSUE TITLE
[AWS::DynamoDB::GlobalTable] -  Drift Detection false positive for KMSMasterKeyId property under AWS::DynamoDB::GlobalTable resource

### ISSUE THREAD

**Issue by AmitaMp** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2232]
### Name of the resource

AWS::DynamoDB::GlobalTable

### Issue Description

The "KMSMasterKeyId" property for the AWS::DynamoDB::GlobalTable resource is marked as drifted, even though there is no actual drift. The CloudFormation template is generated by the CDK using a higher-level construct to create the DynamoDB.

### Expected Behavior

The KMSMasterKeyId property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The KMSMasterKeyId property is marked as NOT_EQUAL with
expected = arn:aws:kms:eu-central-1:1234567891:key/xxxx-xxxx-xxxx-xxxx
actual = xxxx-xxxx-xxxx-xxxx

### Test Cases

Test Cases
Steps to reproduce -

1. Create Stack using following CDK code snippet:
```
this.dbTableScoring = new dynamoDB.TableV2(this, 'scoring_table', {
      partitionKey: { 
        name: 'score_id', 
        type: dynamoDB.AttributeType.STRING 
      },
      globalSecondaryIndexes: [
        {
          indexName: 'test_id_index',
          partitionKey: { 
            name: 'test_id', 
            type: dynamoDB.AttributeType.STRING 
          },
          projectionType: dynamoDB.ProjectionType.ALL
        }
      ],
      removalPolicy: databaseRetentionPolicy,
      deletionProtection: props.enableDeletionProtection,
      timeToLiveAttribute: 'expire_at',
      encryption: dynamoDB.TableEncryptionV2.customerManagedKey(props.dynamoDbKmsKey),
    
    });
  }

```
2. Run drift detection
3. View drift results

**Comment by rgoltz** [comment]
@AmitaMp - I tried to replicate this issue using the following template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Minimal repro for GlobalTable KMSMasterKeyId drift (#2232)"

Resources:
  TableKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Test key for DynamoDB GlobalTable drift repro
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRoot
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  GlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: drift-bug-2232-test
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      Replicas:
        - Region: !Ref "AWS::Region"
          SSESpecification:
            KMSMasterKeyId: !GetAtt TableKey.Arn
```

I triggered the Drift Detection - The stack remained IN_SYNC:
<img width="1315" height="875" alt="Image" src="https://github.com/user-attachments/assets/ebe214a5-97fa-43ff-ac7e-5229ccbbb3e4" />

Do you still see the issue? 
Could you share the JSON-CloudFormation-Template (generated by CDK)?
