### ISSUE TITLE
[AWS::Bedrock::Agent] - [cross-region inference profiles not supported in cfn] - 

### ISSUE THREAD

**Issue by niklas-palm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2235]
### Name of the resource

Other

### Resource Name

AWS::Bedrock::Agent

### Issue Description

The FoundationModel property of the agent resource should accept a cross-region inference profile ARN or ID, but cloudformation returns access denied.

Region: us-west-2

### Expected Behavior

Should allow the ARN or ID of inference profile.

### Observed Behavior

```bash
Resource handler returned message: "Access denied for operation 'AWS::Bedrock::Agent'."
```

### Test Cases

```yaml
  MyAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: my-agent
      Description: "Agent for accomplishing things"
      IdleSessionTTLInSeconds: 1800
      FoundationModel: anthropic.claude-3-5-haiku-20241022-v1:0
      # FoundationModel: arn:aws:bedrock:us-west-2:641758013508:inference-profile/us.amazon.nova-lite-v1:0
      # FoundationModel: us.amazon.nova-lite-v1:0
```

`anthropic.claude-3-5-haiku-20241022-v1:0`works as expected, because that model exists on-deman in the region. The Nova models are only support via cross-region-inference in us-west-2, and in the console UI I can manually configure the agent to use the inference profiles.

### Other Details

- [Cloudformation agent resource docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrock-agent.html)
- Region: us-west-2
- Inference profiles tried, but failed: 
   -  `arn:aws:bedrock:us-west-2:641758013508:inference-profile/us.amazon.nova-lite-v1:0`
   - `us.amazon.nova-lite-v1:0`
