### ISSUE TITLE
[AWS::SageMaker::Domain] - [Coverage] - Missing support to HiddenInstanceTypes property in StudioWebPortalSettings on CloudFormation

### ISSUE THREAD

**Issue by nroshanr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2250]
### Name of the resource

AWS::SageMaker::Domain

### Description

[AWS::SageMaker::Domain StudioWebPortalSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-domain-studiowebportalsettings.html) currently does not support ` HiddenInstanceTypes ` property.
 
This is supported in [API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_StudioWebPortalSettings.html) and CLI
[create-domain](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/create-domain.html)
[update-domain](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/update-domain.html)

When using the `HiddenInstanceTypes` property, CloudFormation gives the following error:
```
[#/DefaultUserSettings/StudioWebPortalSettings: extraneous key [HiddenInstanceTypes] is not permitted]
```

Sample template to replicate the issue:
```
Resources:
  SageMakerResource:
    Type: AWS::SageMaker::Domain
    Properties:
      AuthMode: IAM
      DefaultUserSettings: 
        StudioWebPortalSettings:
            HiddenInstanceTypes:
              - ml.r6id.32xlarge
      DomainName: domainname
      SubnetIds: 
        - subnet-abc
      VpcId: vpc-abc
```
