### ISSUE TITLE
AWS::ElasticBeanstalk::Environment-Properties-OptionSettings[namespace==`aws:elasticbeanstalk:application:environment`].Value should support Dynamic References to AWS Systems Manager Parameter Store Secure Strings

### ISSUE THREAD

**Issue by candrews** [aws-cloudformation/aws-cloudformation-coverage-roadmap#227]
``AWS::ElasticBeanstalk::Environment-Properties-OptionSettings[namespace==`aws:elasticbeanstalk:application:environment`].Value`` (environment variables values) should support Dynamic References to AWS Systems Manager Parameter Store Secure Strings.

Currently, [Dynamic References to AWS Systems Manager Parameter Store Secure Strings are only supported in a limited set of places](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#template-parameters-dynamic-patterns-resources). It would be nice if they were supported in [Beanstalk environment variable values](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkapplicationenvironment) (which are specified in CloudFormation at ``AWS::ElasticBeanstalk::Environment-Properties-OptionSettings[namespace==`aws:elasticbeanstalk:application:environment`].Value``).

This should would allow the Beanstalk application to see an environment variable named `` with value `supersecret` when defined by this CloudFormation template fragment:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Resoures:
  BeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      OptionSettings:
        -
          Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: SPRING_DATASOURCE_PASSWORD
          Value: !Sub "{{resolve:ssm-secure-env:/my/parameter:42}}"
```

**Comment by candrews** [comment]
[It's possible to hack something like this using an ebextension today](https://candrews.integralblue.com/2019/10/using-dynamic-references-to-aws-systems-manager-parameter-store-secure-strings-with-elastic-beanstalk/), but it really should be easier and supported directly in AWS.

**Comment by eballetbaz** [comment]
For information, this feature is already **partially** implemented into Beanstalk.
It is working with non-secure parameters which specify the version:

i.e.:
{{resolve:ssm:DB_PASSWORD:1}}

I tested with platform : 
Tomcat 8.5 with Java 8 running on 64bit Amazon Linux/3.3.0

Other options are not working (but pattern is recognized) 

Secure reference, i.e. {{resolve:ssm-secure:DB_PASSWORD:1}} shows error:

`Service:AmazonCloudFormation, Message:SSM Secure reference is not supported in: [AWS::CloudFormation::WaitConditionHandle/Metadata/AWS::ElasticBeanstalk::Ext/Parameters/EnvironmentVariables,AWS::AutoScaling::AutoScalingGroup/Metadata/AWS::ElasticBeanstalk::Ext/_ContainerConfigFileContent/optionsettings/aws:elasticbeanstalk:application:environment]`

References without version, i.e. {{resolve:ssm-secure:DB_PASSWORD}} shows error:

`Service:AmazonCloudFormation, Message:Incorrect format is used in the following SSM reference: [{{resolve:ssm-secure:DB_PASSWORD}}]`

**Comment by paulmwatson** [comment]
Thanks @candrews but the formatting in your linked article has lost line breaks and indents. Would you mind pasting it again?

**Comment by candrews** [comment]
> Thanks @candrews but the formatting in your linked article has lost line breaks and indents. Would you mind pasting it again?

Woops! I've fixed the article's formatting.

**Comment by amsinha2** [comment]
Is there any new on whether this will work?

**Comment by alex-all3dp** [comment]
I would love for something like this to be possible as well! It would be great if a `.ebextensions` config file could look like

```yaml
option_settings:
  aws:elasticbeanstalk:application:environment:
    DB_USER: '{{resolve:secretsmanager:secretId:SecretString:DB_USER}}'
    DB_PWD: '{{resolve:secretsmanager:secretId:SecretString:DB_PWD}}'
```
