### ISSUE TITLE
[AWS::ApplicationInsights::Application] - [BUG] - `Tier` parameter have wrong Pattern making configuration unusable

### ISSUE THREAD

**Issue by germiBest** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2286]
### Name of the resource

AWS::ApplicationInsights::Application

### Issue Description

There is a validation issue with the Tier attribute inside the ComponentMonitoringSetting property. The documentation lists valid values such as DEFAULT, SQL_SERVER, etc., but the schema includes a regex pattern ^[A-Z][[A-Z]_]*$, which is malformed and blocks all allowed values. The pattern incorrectly contains double square brackets [[A-Z]_]*, making it impossible to deploy resources using CloudFormation.

AWS Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationinsights-application-componentmonitoringsetting.html

### Expected Behavior

The Tier attribute should accept valid values as specified in the documentation, such as DEFAULT, SQL_SERVER, POSTGRESQL, etc. The regular expression pattern should be corrected to accurately reflect these allowed values.

### Observed Behavior

Using any valid Tier value results in a validation error. For example, setting:
```yaml
Tier: DEFAULT
```
Produces the following error:
```
E3031 'DEFAULT' does not match '^[A-Z][[A-Z]_]*$'
```

### Test Cases

Attempting to deploy a CloudFormation stack with the following configuration:

```yaml
...
Resources:
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: "app-resource-group"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: "app-resource-group"
      AutoConfigurationEnabled: 'false'
      OpsCenterEnabled: 'true'
      OpsItemSNSTopicArn: !Ref SupportTopic
      CustomComponents:
        - ComponentName: "ApiLambda"
          ResourceList:
            - !GetAtt Function.Arn
      ComponentMonitoringSettings:
        - ComponentName: "ApiLambda"
          Tier: DEFAULT
          ComponentConfigurationMode: DEFAULT
    DependsOn: ApplicationResourceGroup
```

Results in following validation error:
`E3031 'DEFAULT' does not match '^[A-Z][[A-Z]_]*$'`

### Other Details

This issue prevents the use of the AWS::ApplicationInsights::Application resource with custom ComponentMonitoringSetting configurations, hindering the deployment of applications that rely on this functionality.

Reference: [AWS Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationinsights-application-componentmonitoringsetting.html)

This issue is critical as it blocks production deployments using AWS::ApplicationInsights::Application with custom ComponentMonitoringSetting configurations.
