### ISSUE TITLE
[Resource Type] - [Enhancement] - Dynamic messageGroupId feature in AWS EventBus

### ISSUE THREAD

**Issue by vinnyxxx** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2298]
### Name of the resource

AWS::Events::EventBus

### Description

Hi Team,

We are requesting support for a dynamic messageGroupId feature in AWS EventBridge rules. Currently, the messageGroupId is statically set—often to a fixed value—which causes all messages routed to an AWS FIFO queue to share the same group ID. This results in significant processing inefficiencies, as the FIFO queue enforces strict ordering within a message group, allowing only a single consumer to process messages sequentially. Enabling dynamic assignment of messageGroupId would allow better parallelism and throughput by distributing messages across multiple message groups.

**Comment by kcwinner** [comment]
Ran into a situation today where I needed this. I'd like the `Exactly-once processing` guarantee from FIFO since our workload has a large volume of S3 -> EB -> SQS and we are receiving the occasional duplicate. It'd be nice to not have to go from EB -> Lambda -> SQS -> Lambda 

Related: https://github.com/aws/aws-cdk/issues/32965

**Comment by EvanK** [comment]
A killer feature for this would be the ability to set the messageGroupId **from a JSON path of the source event**.

Grouping S3 events by object key, for example:

```yaml
Type: AWS::Events::Rule
Properties:
  Targets: 
    -
      Arn: arn:aws:sqs:us-west-2:081035103721:demoSQS.fifo
      Id: QueueTargetWithDynamicMessageGroup
      SqsParameters:
        MessageGroupId: "$.detail.object.key"
```
