### ISSUE TITLE
AWS::ElasticLoadBalancingV2::Target

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/aws-cloudformation-coverage-roadmap#230]
## 2. Scope of request 
Currently it is possible to register targets during the creation of an AWS::ElasticLoadBalancingV2::TargetGroup using the Targets: property, unfortunately in the case of a Lambda with a SourceArn permission this creates a circular dependency since the target can't be registered until the permission is added, but the permission can't be added until the TargetGroup ARN is known (ie the TargetGroup has been created).

One option would be to have the TargetGroup resource add permissions automatically in the same way that the console does, which would be convenient, but I suspect that it would be more flexible to simply seperate the registration of a target to a target group into it's own resource, then the TargetGroup could be created without the target, allowing the permission to be added, after which the target could be registered to the existing group.

## 3. Expected behavior
It should be possible to create and register a Lambda function to a TargetGroup in without requiring that access to the function be granted open permissions (ie by not specifying a SourceArn in the  permission)

It may make sense to allow the registration resource to accept a list of targets in the same was as the existing Targets property of the AWS::ElasticLoadBalancingv2::TargetGroup

## 4. Suggest specific test cases
Create and associate a Lambda function as an ALB request handler in a single CloudFormation stack.

## 5. Helpful Links to speed up research and evaluation
RegisterTargets API -https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_RegisterTargets.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
1. Compute (EC2, ECS, EKS, Lambda...)
4.  Networking & Content (VPC, Route53, API GW,...)
8. Security (IAM, KMS...)

**Comment by sturdiva** [comment]
We could also benefit from this, we have a few patterns where we create a `base` stack for a service (which typically contains a security group, IAM role, instance profile, and load balancer), and then instantiate an arbitrary number of `server` stacks, where the servers would then need to be registered with the target group.

Currently we accomplish this via manually updating a parameter on the base stack, but it would be nice to be able to register the servers in the same template that creates them (de-coupled from the target group creation)

**Comment by ikben** [comment]
This would also make it possible to have your targets in a different stack from the target group, which unlocks more deployment options.

**Comment by penguinwan** [comment]
I workaround this issue by, have a default permission so that target group can be created, have another permission specifying sourceArn=target group, have a custom resource remove default permission after target group has been created.
```
DefaultPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName: ...
    Principal: elasticloadbalancing.amazonaws.com

TargetGroup:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  DependsOn:
    - DefaultPermission
  Properties:
    TargetType: lambda
    Targets:
      - Id: ...

RealPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName:...
    Principal: elasticloadbalancing.amazonaws.com
    SourceArn: !Ref TargetGroup

RemoveDefaultPermission:
  Type: Custom::RemoveDefaultPermission
  DependsOn:
    - TargetGroup
    - RealPermission
  Properties:
    ServiceToken: ...
```

**Comment by stuartloy** [comment]
+1 for this issue.

@penguinwan Are you able to share more details on how your custom resource works to delete the original permission?

**Comment by penguinwan** [comment]
> +1 for this issue.
> 
> @penguinwan Are you able to share more details on how your custom resource works to delete the original permission?

I use Javascript and `cfn-lambda`, should work without `cfn-lambda` as well. 
You can have `FunctionName` hardcoded in the JS, or passed in from custom resource properties like below:
```
RemoveDefaultPermission:
  Type: Custom::RemoveDefaultPermission
  DependsOn:
    - TargetGroup
    - RealPermission
  Properties:
    ServiceToken: ...
    FunctionName: (here)
```
Lambda's index.js, removes all permission that has no `SourceArn` specified.
```
const CfnLambda = require('cfn-lambda');
const AWS = require('aws-sdk');
const lambda = new AWS.Lambda({ apiVersion: '2015-03-31'});

async function AsyncCreate(CfnRequestParams) {

    const functionName = CfnRequestParams.FunctionName;
    const getPolicyResponse = await lambda.getPolicy({
        FunctionName: functionName
    }).promise();

    JSON.parse(getPolicyResponse.Policy).Statement.forEach(async function (statement) {
        if (!statement.Condition) {
            await lambda.removePermission({
                FunctionName: functionName,
                StatementId: statement.Sid
            }).promise();
        }
    });

    return {};
}
async function AsyncUpdate() {}
async function AsyncDelete() {}

exports.handler = CfnLambda({
    AsyncCreate,
    AsyncUpdate,
    AsyncDelete,
});
```

**Comment by jorgechen** [comment]
What if you update the logic for the TargetGroup permission check so that CloudFormation can detect `AWS::Lambda::Permission` if it is present? 

Why does CloudFormation **mandate** the permission check before deploying the TargetGroup? How about allowing the user the ability to disable the permission check?

**Comment by tengineerio** [comment]
+1 please

**Comment by dgard1981** [comment]
AWS have proved [this blog post](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-lambda-dependency/) which suggests using a Lambda custom resource. IMO it's not really a solution though, just avoidance of the actual underlying issue with a hacky workaround that will make AWS more money.

The closest I have come to a proper solution is to add a `Name` to the Target Group, and then I'm able to add a wildcard `SourceArn` to the Lambda permission. This came from a StackOverflow answer, though I can't find it again now so can't provide the link.

```
Resources:
  ...

  ProxyFunctionPermission:
    Type: AWS::Lambda::Permission # This resource does not support tags.
    Properties:
      FunctionName: !GetAtt ProxyFunction.Arn
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/MyTargetGroup/*

  ProxyFunctionTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ProxyFunctionPermission
    Properties:
      Name: MyTargetGroup
      TargetType: lambda
      Targets:
      - Id: !GetAtt ProxyFunction.Arn
```
