### ISSUE TITLE
[Audit Manager] - [Coverage] - Support AWS::AuditManager::Control

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2320]
### Name of the resource

AWS::AuditManager::Assessment

### Resource name

AWS::AuditManager::Control

### Description

Currently there are no CloudFormation resource type for AuditManager Control. It will be good if there is native support for it.

```
Type: AWS::AuditManager::Control
Properties:
  Name: String
  Description: String
  TestingInformation: String
  ActionPlanTitle: String
  ActionPlanInstructions: String
  ControlMappingSources:
    - ControlMappingSource
  Tags: 
    - Tag
```

```
Property: ControlMappingSource

SourceName: String
SourceDescription: String
SourceSetUpOptoin: 'System_Controls_Mapping'|'Procedural_Controls_Mapping'
SourceType: 'AWS_Cloudtrail'|'AWS_Config'|'AWS_Security_Hub'|'AWS_API_Call'|'MANUAL'|'Common_Control'|'Core_Control',
SourceKeyword: SourceKeyword
SourceFequency: 'DAILY'|'WEEKLY'|'MONTHLY'
TroubleshootingText: String

Property: SourceKeyword

KeywordInputType: 'SELECT_FROM_LIST'|'UPLOAD_FILE'|'INPUT_TEXT'
KeywordValue: String
```

Source:
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/auditmanager/client/create_control.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/auditmanager/client/update_control.html
