### ISSUE TITLE
[Resource Type] - [Docs] - Improve documentation clarity for OpenSearchServerless Index Mappings Properties notation

### ISSUE THREAD

**Issue by gitkanta** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2336]
### Name of the resource

Other

### Resource name

AWS::OpenSearchServerless::Index

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-opensearchserverless-index-mappings.html

## Issue Description
The current documentation for AWS::OpenSearchServerless::Index Mappings Properties is unclear about the required key-value pair notation structure. This makes it difficult for users to understand how to properly format their CloudFormation templates.

## Current Documentation
The current documentation at [AWS::OpenSearchServerless::Index Mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-opensearchserverless-index-mappings.html) doesn't provide clear examples of the required structure.

## Example of Invalid Template
```yaml
Mappings:
  Properties:
    Dimension: 1536
    Type: knn_vector
```
## Example of Valid Template
```yaml
Mappings:
  Properties:
    test:  # Required field name
      Dimension: 1536
      Type: knn_vector
```

## Suggested Improvements
- Add complete working examples to the documentation
- Clarify that a field name is required as a key in the Properties object
- Include more detailed explanation of the structure and its requirements
- Add common use cases and their corresponding template structures
### This improvement would help users:
- Avoid trial and error when creating templates
- Better understand the required structure
- Save time in template development
- Reduce support queries related to this issue
- 
Would you please consider updating the documentation to make it more clear and user-friendly?
