### ISSUE TITLE
AWS::EC2::Subnet - False-positive drift on Ipv6CidrBlock property

### ISSUE THREAD

**Issue by keegannnn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2337]
### Name of the resource

AWS::EC2::Subnet

### Issue Description

Drift detection falsely says that the Ipv6CidrBlock property's value is drifted.

### Expected Behavior

The values returned in the drift report should both reflect the same version of the Ipv6CidrBlock property's value.

### Observed Behavior

The false-positive drift appears to be because a canonical version of the CIDR is returned and compared to a non-canonical version of it, in the drift evaluation workflow.

### Test Cases

Deploy the CloudFormation template below and immediately run drift detection on the stack:
```
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default

  IPV6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: AWS::Region
      Ipv6Native: true
      Ipv6CidrBlock: !Select 
        - 0
        - !Cidr 
          - !Select 
            - 0
            - !GetAtt VPC.Ipv6CidrBlocks
          - 1
          - 64
      AssignIpv6AddressOnCreation: true
      MapPublicIpOnLaunch: false 
```
