### ISSUE TITLE
AWS::Events::Rule->EventPattern - Ability to supply a integer value

### ISSUE THREAD

**Issue by Guslington** [aws-cloudformation/aws-cloudformation-coverage-roadmap#251]
## 1. Title
AWS::Events::Rule->EventPattern - Ability to supply a integer value

## 2. Scope of request 
Ability to supply a integer value in a cloudwatch event pattern

## 3. Expected behavior

On create or update supply a integer value in a cloudwatch event pattern, however cloudformation converts that value to a string. Integer values are required for guardduty severity.

## 4. Suggest specific test cases

Example event pattern for guardduty

```json
{
      "detail-type": [
        "GuardDuty Finding"
      ],
      "source": [
        "aws.guardduty"
      ],
      "detail": {
        "severity": [
          5,8
        ]
    }
}
```

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html#guardduty_cloudwatch_example

**Comment by michaelwittig** [comment]
This bug get's more relevant with the new filter capabilities:

```yaml
  ECRIMageScanFindingEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
        - 'aws.ecr'
        'detail-type':
        - 'ECR Image Scan'
        detail:
          finding-severity-counts:
            CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
            HIGH: [{exists: false}, {numeric: ['>', 0]}]
            MEDIUM: [{exists: false}, {numeric: ['>', 0]}]
            UNDEFINED: [{exists: false}, {numeric: ['>', 0]}]
```

is turned into:
```json
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "HIGH": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "MEDIUM": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "UNDEFINED": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "CRITICAL": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ]
    }
  }
}
```

which results in all kinds of validation errors.

instead of:

```json
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "HIGH": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "MEDIUM": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "UNDEFINED": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "CRITICAL": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ]
    }
  }
}
```

**Comment by jogold** [comment]
@TheDanBlanco any update on this? Really frustrating to see that the [new advanced event patterns](https://aws.amazon.com/blogs/compute/reducing-custom-code-by-using-advanced-rules-in-amazon-eventbridge/) cannot be deployed via CloudFormation.

**Comment by TheDanBlanco** [comment]
nothing yet. there are other items with higher +1's that we're working on right now. i'll keep an eye on this though

**Comment by jogold** [comment]
Thanks for the feedback @TheDanBlanco.

Just to be clear, it's not really a coverage issue here but rather a bug. CloudFormation stringifies everything in `AWS::Events::Rule.EventPattern` (numbers, booleans) and this leads to validation errors from CloudWatch Events.

**Comment by jmnarloch** [comment]
I had created initial pull request for dedicated builder: https://github.com/aws/aws-cdk/pull/6414

**Comment by stevecaldwell77** [comment]
@TheDanBlanco: the example by @michaelwittig above shows that this issue is not just integers, but booleans too. Just wanted to explicitly call that out so it didn't go unnoticed! Not being able to use an exists pattern is really limiiting.

**Comment by jackcbrown89** [comment]
@TheDanBlanco Any status updates on a fix for this? This blocks us from writing many of our event patterns in CF templates.

**Comment by ljacobsson** [comment]
Also interested in an update on this. EventBridge is a very potent service, but this bug makes it very unattractive to adopt for any team. We're ending up writing ugly workarounds which is getting painful. 

Imho this is more of a bug than a feature request and there must be internal interest from the EventBridge team to get this fixed. Is it solely prioritised based on upvotes or do we have a chance to see this fixed in the near future?

**Comment by stevecaldwell77** [comment]
@ljacobsson - a fix is supposedly rolling out: https://twitter.com/nickste/status/1237036312571437059

**Comment by ljacobsson** [comment]
@stevecaldwell77 yes I was following the rollout of that one, but it got pulled back. 

I'm tracking this through various threads and just learnt from  [here](https://github.com/awslabs/serverless-application-model/issues/1455) that a fix is rolling out very soon 👍

**Comment by ritchieleeann** [comment]
Any updates on this? That Twitter thread said there'd be **another** update on ETA last week.

**Comment by sukdeb-gitlab** [comment]
I can confirm the above pattern works as expected now, probably the fix has been applied:-
{
      "detail-type": [
        "GuardDuty Finding"
      ],
      "source": [
        "aws.guardduty"
      ],
      "detail": {
        "severity": [
          5,8
        ]
    }
}

**Comment by michaelwittig** [comment]
I can not confirm that it works.

Pattern:
```yaml
EventPattern:
  source:
  - 'aws.ecr'
  'detail-type':
  - 'ECR Image Scan'
  detail:
    finding-severity-counts:
      CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
      HIGH: [{exists: false}, {numeric: ['>', 0]}]
      MEDIUM: [{exists: false}, {numeric: ['>', 0]}]
      UNDEFINED: [{exists: false}, {numeric: ['>', 0]}]
```

Error:

Event pattern is not valid. Reason: exists match pattern must be either true or false. at [Source: (String)"{"detail-type":["ECR Image Scan"],"source":["aws.ecr"],"detail":{"finding-severity-counts":{"HIGH":[{"exists":"false"},{"numeric":[">","0"]}],"MEDIUM":[{"exists":"false"},{"numeric":[">","0"]}],"UNDEFINED":[{"exists":"false"},{"numeric":[">","0"]}],"CRITICAL":[{"exists":"false"},{"numeric":[">","0"]}]}}}"; line: 1, column: 112] (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: InvalidEventPatternException; Request ID: d4f20cd8-1edc-4e63-b55b-ab7339111615)
--
