### ISSUE TITLE
AWS::CloudFormation::RegisterType

### ISSUE THREAD

**Issue by pgarbe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#266]
## 1. Title 
AWS::CloudFormation::RegisterType

## 2. Scope of request 
AWS::CloudFormation::RegisterType - can create resource via API, but not via CloudFormation

## 3. Expected behavior
In Create, the RegisterType should be registered, and in Delete it should be unregistered. It seems that updates are not supported.

## 4. Suggest specific test cases
Just being able to do the same stuff as with the API / CLI.

## 5. Helpful Links to speed up research and evaluation
See `registerType` and `deregisterType` in https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

5. Management (CloudTrail, Config...)

**Comment by rjlohan** [comment]
We are working on this one, we just have some back and forth on the right model here mainly with respect to setting default versions and how that should best work in  CloudFormation stack. 👍🏼

**Comment by benkehoe** [comment]
Why not put that discussion about how default versions should be managed here on the roadmap, and let customers give feedback on the options?

**Comment by rjlohan** [comment]
So the way we are thinking about this type is that you'd have a model something like below (represented as a CloudFormation template snippet);

```
Type: AWS::CloudFormation::Type
Properties:
    Kind: Resource
    TypeName: Organisation::Service::Resource
    DefaultVersion: "00000003"
    ExecutionRoleArn: arn:aws:iam::123456789012:role/MyExecutionRole
    SchemaHandlerPackage: my-artifact-bucket
    LoggingConfiguration:
        LogRoleArn: arn:aws:iam::123456789012:role/MyLoggingRole
        LogGroupName: MyResourceLogGroups
```

The `!Ref`-able identity of this type would be the [TypeArn](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_TypeSummary.html) 

Provisioning semantics;

* On _Create_ a new type would be registered with the [`RegisterType` API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RegisterType.html), and we would expect the _Create_ action to fail if a type of this `Kind|TypeName` already existed in your account. 
* _Update_ would be supported _only_ for the `DefaultVersion` field; all other fields are `createOnlyProperties` and would create a new version of the type
* _Delete_ would call the [`DeregisterType` API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DeregisterType.html)

I think that's the gist of the discussion I have had with @aygold92 so far.
