### ISSUE TITLE
AWS::Include in us-gov-east-1, cn-north-1 and cn-northwest-1

### ISSUE THREAD

**Issue by honglu** [aws-cloudformation/aws-cloudformation-coverage-roadmap#278]
## 1. Title 
AWS::Include in us-gov-east-1, cn-north-1 and cn-northwest-1

## 2. Scope of request 
AWS::Include exists in all regions except us-gov-east-1, cn-north-1 and cn-northwest-1

## 3. Expected behavior

A template with AWS::Include should be able to deploy successfully in us-gov-east-1, cn-north-1 and cn-northwest-1

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation
Background: We are using DefinitionBody in AWS::ApiGateway::RestApi resource to specify API definition. AWS::Include allows storing the API definition file in S3 when it is very big while we can still take advantages of CloudFormation intrinsics functions in API definition file such as the Lambda ARN

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Storage - S3
2. Networking & Content - API GW

**Comment by PatMyron** [comment]
[`AWS::Include`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html) should be available in `cn-north-1`, `cn-northwest-1`, `af-south-1`, and `eu-south-1` now

[found other transforms that aren't globally available too](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/761). Generalizing this issue

**Comment by zetas** [comment]
I hope this is the right place to post this, it's bewildered me for awhile and I can't find anyone else on the internet that seems to be having the same issue. Either no one is trying to use `AWS::Transform` in GovCloud or there's something wrong with my account. When I try to use a template that worked fine in the regular AWS partition with an include transform it fails in GovCloud saying: `Embedded stack arn:aws-us-gov:cloudformation:us-gov-east-1:ACCTNUM:stack/tCaT-cf-test-default-5e302e1a1bff47be820d6d02374e3e22-RDSStack-1SWPF25EEFHU5/fdd47ad0-2908-11eb-9329-0eabfe23e8f8 was not successfully created: No transform named AWS::Include found.`

Here's the resource that's attempting to use it:

```yaml
  Instance:
    Type: 'AWS::RDS::DBInstance'
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3001
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub 's3://${S3SourceBucketName}/${CPVersion}/templates/customer/rds-instance-${StackType}-policy.yaml'
    Properties:
      Engine: MySQL
      EngineVersion: '5.7'
      MultiAZ: !Ref MultiAZ
      MasterUsername: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          - !Ref InstanceMasterCredentials
          - ':SecretString:username}}'
      MasterUserPassword: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          - !Ref InstanceMasterCredentials
          - ':SecretString:password}}'
      DBInstanceClass: !Ref InstanceType
      StorageType: gp2
      AllocatedStorage: !Ref InitialAllocatedStorage
      MaxAllocatedStorage: !Ref MaxAllocatedStorage
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups: !Split
        - ","
        - !Ref VPCSecurityGroupIds
      StorageEncrypted: true
      KmsKeyId: !Ref EncryptionKeyId
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBSnapshotIdentifier:
        Fn::If:
          - UseSnapshot
          - Ref: RDSSnapShotIdentifier
          - Ref: AWS::NoValue
      DBParameterGroupName:
        Fn::If:
          - UseBISlave
          - Ref: BIReplicationParamGroup
          - Ref: AWS::NoValue
```

again this works fine in every region I've tried it in in the regular AWS partition so I'm not sure what's going on. Any light you guys can shed would be super helpful because I'm effectively stuck without this. No way to dynamically set policies without it :(
