### ISSUE TITLE
AWS::ApiGatewayV2::Api-GetAtt-Arn

### ISSUE THREAD

**Issue by iconara** [aws-cloudformation/aws-cloudformation-coverage-roadmap#294]
## Scope of request

`AWS::ApiGatewayV2::Api` does not support `GetAtt`.

## Expected behavior

It should be possible to use `GetAtt` with a `AWS::ApiGatewayV2::Api` to get the ARN of the resource, e.g. `!GetAtt MyApi.Arn`.

## Suggest specific test cases

```
Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Lambda Proxy
      Description: Lambda proxy using quick create
      ProtocolType: HTTP
      Target: !Ref Function # this resource has been omitted for brevity

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Function.Arn # this resource has been omitted for brevity
      Principal: apigateway.amazonaws.com
      SourceArn: !GetAtt Api.Arn # this does not work
```

## Category (required)

Networking & Content (API GW)
