### ISSUE TITLE
Add AWS::Include functionality to Fn::Sub

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#310]
There are a lot of large documents that exist on CloudFormation resources. API Gateway swagger, definitions for Step Functions, CodePipeline, and CodeBuild, etc.

It would be convenient to store the document as a separate file. The `AWS::Include` transform exists to help with this, but it does not suffice for two reasons:
* The syntax of a file used with `AWS::Include` is still CloudFormation. These documents are the value of a single property, and have their own internal syntax; the file should just contain the document, not the surrounding CloudFormation property key (which is what's required for `AWS::Include`); this would let the files undergo validation that doesn't need to understand CloudFormation at all.
* The document must reference other resources in the rest of the template (for example, the Lambda function ARNs inside a state machine), but now you have a sort of circular reference problem: you have to keep this document in sync with changes to the template, for example if a logical id of a resource changes in the template, how does the developer making that change know if that resource is referenced in any included documents?

I have been asking individual teams to add the functionality in their APIs to retrieve these documents from S3, and additionally to add environment variable-like along with it, so that the document need not be hard-coded with certain references. But maybe CloudFormation could add a native capability to solve this.

Suppose `Fn::Sub` was extended to allow retrieving the template string from S3, performing the substitution as well as optionally parsing the result into the `Json` CloudFormation type (so the document could be either JSON or YAML independent of the template's syntax). The "environment variable" aspect comes from the existing semantics of `Fn::Sub`. The SAM CLI could understand an `Fn::Sub` with a `CodeUri` and automatically perform the upload.

What this would look like for the example in the `AWS::CodePipeline::Pipeline` resource docs ([link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html)):

The template snippet:
```yaml
AppPipeline: 
  Type: AWS::CodePipeline::Pipeline 
  Properties: 
    RoleArn:
      !Ref: CodePipelineServiceRole 
    Stages: 
      !SubS3
        - s3://my-bucket/my-stages.yaml
        - SourceS3Bucket: !Ref MyBucket
          SourceS3ObjectKey: "my-key"
          ApplicationName: !Ref ApplicationName
          DeploymentGroupName: !Ref DeploymentGroupName
    ArtifactStore: 
      Type: S3 
      Location:
        Ref: ArtifactStoreS3Location 
      EncryptionKey:
        Id: arn:aws:kms:useast-1:ACCOUNT-ID:key/KEY-ID
        Type: KMS
    DisableInboundStageTransitions: 
      - 
        StageName: Release 
        Reason: "Disabling the transition until integration tests are completed"
    Tags:
      - Key: Project
        Value: ProjectA
      - Key: IsContainerBased
        Value: 'true'
```

The contents of `s3://my-bucket/my-stages.yaml`:
```yaml
- Name: Source 
  Actions: 
  - Name: SourceAction
	ActionTypeId: 
	  Category: Source 
	  Owner: AWS 
	  Version: 1 
	  Provider: S3 
	OutputArtifacts: 
	  - 
		Name: SourceOutput 
	Configuration: 
	  S3Bucket: ${SourceS3Bucket}
	  S3ObjectKey: ${SourceS3ObjectKey}
	RunOrder: 1 
- Name: Beta 
  Actions: 
  - Name: BetaAction 
	InputArtifacts: 
	  - Name: SourceOutput 
	ActionTypeId: 
	  Category: Deploy 
	  Owner: AWS 
	  Version: 1 
	  Provider: CodeDeploy
	Configuration: 
	  ApplicationName: ${ApplicationName}
	  DeploymentGroupName: ${DeploymentGroupName}
	RunOrder: 1 
- Name: Release 
  Actions: 
  - Name: ReleaseAction
	InputArtifacts: 
	  - Name: SourceOutput 
	ActionTypeId: 
	  Category: Deploy 
	  Owner: AWS 
	  Version: 1
	  Provider: CodeDeploy 
	Configuration: 
	  ApplicationName: ${ApplicationName}
	  DeploymentGroupName: ${DeploymentGroupName}
	RunOrder: 1 
```
