### ISSUE TITLE
Support kms:ViaService for KMS key operations

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/aws-cloudformation-coverage-roadmap#321]
It would be great if CloudFormation became a supported service for the kms:ViaService condition as per:

https://docs.aws.amazon.com/kms/latest/developerguide/policy-conditions.html#conditions-kms-via-service

This would allow me to create a KMS key policy that enforces that only operations performed by CloudFormation are permitted for certain actions (for example, encrypting Lambda function environment variables).

Categories: Security (KMS), Enhancement

**Comment by acdebaca** [comment]
Hi @iann0036:
This already works today. We have used this feature specifically for encrypting lambda function environment variables. For example:
```
       - Sid: CFRoleEncryptLambda
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::123456789012:role/cloudformation-role
          Resource: "*" 
          Action:
          - kms:Encrypt
          Condition:
            StringEquals:
              kms:ViaService: cloudformation.us-east-1.amazonaws.com
```
...and you would also include a statement for the role assumed by the lambda function allowing `kms:Decrypt`, which could use `kms:ViaService: lambda.us-east-1.amazonaws.com`.

Perhaps you omitted the region in the DNS name in your own testing? It's not the same DNS name that you would include in an assume-role trust policy (e.g. for the lambda function), which does not include the region.

The one problem that we have encountered is that, if you are using [a dedicated CloudFormation service role](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html), then that role must have `kms:PutKeyPolicy` and `kms:CreateKey` specified on the key policy **without any conditions**, or you will receive an error like **The new key policy will not allow you to update the key policy in the future** -- even if you have granted these permissions to another role (e.g. a super user role). It's pretty arbitrary, in fact, which actions succeed and which fail when you specify conditions like `kms:ViaService`. YMMV, Just my $0.02.
