### ISSUE TITLE
Allow Dynamic References for Secure Values in Custom Resources

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#341]
# Scope of request 

Currently, you can use Dynamic References for Secure Values, i.e. `{{resolve:ssm-secure:IAMUserPassword:10}}` in most places. However, it is not possible to use them as parameters (read: arguments) to a Custom Resource. 

This is documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings

Under Addition Considerations:

* Dynamic references for secure values, such as ssm-secure and secretsmanager, are not currently supported in custom resources.

## Samples:

```
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  MyFrontEndTest: 
    Type: "Custom::PingTester"
    Version: "1.0"
    Properties: 
      ServiceToken: "arn:aws:sns:us-east-1:84969EXAMPLE:CRTest"
      Password: {{resolve:ssm-secure:IAMUserPassword:10}} 
Outputs: 
  CustomResourceAttribute1: 
    Value: 
      Fn::GetAtt: 
        - MyFrontEndTest
        - responseKey1
  CustomResourceAttribute2: 
    Value: 
      Fn::GetAtt: 
        - MyFrontEndTest
        - responseKey2
```

## Expected Behavior:

We should be allowed to use a dynamic reference for secure values on custom resources.

## Helpful links:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html

## Category:
Compute, Security
