### ISSUE TITLE
AWS::S3::BucketPolicy-DeletionPolicy

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/aws-cloudformation-coverage-roadmap#355]
## 2. Scope of request 

   c) new attribute for an existing resource is desired 

AWS::S3::BucketPolicy-DeletionPolicy

## 4. Suggest specific test cases

Specify `"DeletionPolicy": "Retain"` on both `AWS::S3::Bucket` and `AWS::S3::BucketPolicy` to keep the bucket and bucket policy created from a stack.

Common use case: Keeping buckets containing access logs after a stack's resources are deleted.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html#aws-properties-s3-policy-properties

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

2. Storage (S3)

**Comment by TheDanBlanco** [comment]
hi chris,

i can't reproduce this. with a minimal sample template below i created both a bucket & bucket policy both with deletion policies, deleted the stack (both resources show DELETE_SKIPPED), and verified that the resources (bucket plus bucket policy) still stand.

```
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument: 
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${Bucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
```

because i can't reproduce this in any way, i'm closing this issue. i'm happy to reopen if you can provide a scenario where this doesnt work as intended

**Comment by cmckni3** [comment]
Aha, it appears `DeletionPolicy` is supported by any resource and I was missing it on `AWS::S3::BucketPolicy` and is mentioned on the [DeletionPolicy page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).

There's no mention of `DeletionPolicy` on the [BucketPolicy page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html) but the [Bucket page mentions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) mentions it.

I asked AWS support about this and they stated that BucketPolicy in CloudFormation did not support `DeletionPolicy`.

Anyways, below is an example like what I have and indeed works.

```
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          - Action: 's3:Delete*'
            Effect: Deny
            Resource: !Sub 'arn:aws:s3:::${Bucket}'
            Principal:
              AWS: '*'
```

Thanks for the help @TheDanBlanco.
