### ISSUE TITLE
Logical ID renaming behavior (AWS::GuardDuty::Member and AWS::Route53::RecordSet)

### ISSUE THREAD

**Issue by OlafConijn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#363]
AWS::GuardDuty::Member does not support changing the logicalName of the resource.

**problem**: 
If I change the logicalName of a `AWS::GuardDuty::Member` resource (without changing any attribute) this will result in the following error:

`aaaaaa2c5bc2fe8479f24ad8af2a56|123123123123 already exists in stack arn:aws:cloudformation:eu-central-1:123123123123:stack/guardduty/aaaaaa-3d71-11ea-9f1e-0264b9b54242`

**Expected behavior** is that changing a logicalName will result in a no-op.

**Test case**
create a stack using
```
  Member:
    Type: AWS::GuardDuty::Member
    Properties:
      DetectorId: !Ref Detector
      Email: !Ref Email
      MemberId: !Ref CurrentAccount
      Status: Invited
      DisableEmailNotification: true
```
update using:
```
  Member2:
    Type: AWS::GuardDuty::Member
    Properties:
      DetectorId: !Ref Detector
      Email: !Ref Email
      MemberId: !Ref CurrentAccount
      Status: Invited
      DisableEmailNotification: true
```

**Comment by PatMyron** [comment]
[AWS::Route53::RecordSet details](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/364)

**Comment by ikben** [comment]
Isn't this the expected behaviour for the GuardDuty member. And the RecordSet should also throw an error on update?

In my opinion calling it "changing the LogicalId", doesn't really represent what you're doing. You're creating a resource and deleting another one. There is not reason that CloudFormation should know that they are the same (the fact that at this point only one of those can exist in any account is something that only the underlying service can know).

Compare this with how S3 works, if you write this template as step 1:

```yaml
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
```

And update it with either

```yaml
Resources:
  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
```

or 

```yaml
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
```
You will get exactly the same error
