### ISSUE TITLE
AWS::Lambda::Function-Code-ZipFile python3.8

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/aws-cloudformation-coverage-roadmap#370]
## 1. Title 
AWS::Lambda::Function-Code-ZipFile support for python3.8

## 2. Scope of request 
Allow use of "ZipFile" specify code inline in a CloudFormation template, for Lambda functions using the python3.8 runtime.

The AWS Lambda console indicates that python3.8 is the "latest supported" python runtime, but if I try to upgrade my python3.7 functions to python3.8 via CloudFormation, stack update fails with the following error:

> ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7.

## 3. Expected behavior

ZipFile should work with *all* supported nodejs and python runtimes.

## 4. Suggest specific test cases

Deploy a CloudFormation stack with a trivial python3.8 Lambda function using ZipFile to specify the code inline.  For example,

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Test deployment of Lambda function with python3.8'

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: !GetAtt [Role, Arn]
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return True
```

## 5. Helpful Links to speed up research and evaluation

This same issue was reported and closed for node10.x and node12.x in #80 

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

## 7. Any additional context (optional)

Adding support for ZipFile should be part of the standard procedure for adding a new supported runtime to Lambda.
