### ISSUE TITLE
AWS::Route53::VPCAssociationAuthorization

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/aws-cloudformation-coverage-roadmap#371]
https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateVPCAssociationAuthorization.html

## 2. Scope of request 

New support desired for Route53 methods 'CreateVPCAssociationAuthorization' and 'DeleteVPCAssociationAuthorization'

Currently it is not possible to authorize VPCs to associate with a private hosted zone in native CloudFormation.  We are forced to work around this by deploying a Lambda custom resource type, which sucks.

## 3. Expected behavior

A resource type should exist for Route53::VPCAssociationAuthorization.  It should contain the following properties:
- HostedZoneId
- VPCId
- VPCRegion

It might make sense to also add a new property to Route53::HostedZone, to specify a list of VPCs to authorize, e.g.:

```
Type: AWS::Route53::HostedZone
Properties:
  ...
  VPCAssociationAuthorizations:
    - VPCId: vpc-xxxyyy
      VPCRegion: xx-yyyy-1
    - VPCId: ...
      VPCRegion: ...
```

## 4. Suggest specific test cases

A user can successfully authorize a VPC in another account to associate with a private hosted zone, using native CloudFormation.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateVPCAssociationAuthorization.html
https://docs.aws.amazon.com/Route53/latest/APIReference/API_DeleteVPCAssociationAuthorization.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

4.  Networking & Content (VPC, Route53, API GW,...)
