### ISSUE TITLE
AWS::Elasticsearch::Domain-LogPublishingOptions Error Creating Stack

### ISSUE THREAD

**Issue by rileylnapier** [aws-cloudformation/aws-cloudformation-coverage-roadmap#393]
Hi, I am trying to follow this Cloudformation schema to add error logs (ES_APPLICATION_LOGS) via LogsPublishingOptions to my ElasticSearch instance

https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/registry/resourceTypes/details?arn=arn%3Aaws%3Acloudformation%3Aus-east-1%3A%3Atype%2Fresource%2FAWS-Elasticsearch-Domain

```
 "LogPublishingOptions" : {
      "type" : "object",
      "patternProperties" : {
        "[a-zA-Z0-9]+" : {
          "$ref" : "#/definitions/LogPublishingOption"
        }
      }
    },
"LogPublishingOption" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "CloudWatchLogsLogGroupArn" : {
          "type" : "string"
        },
        "Enabled" : {
          "type" : "boolean"
        }
      }
    },
```

In my cloudformation yml  I am using 

```
     LogPublishingOptions: 
        ES_APPLICATION_LOGS: 
            Enabled: true
            CloudWatchLogGroupArn:
              Fn::GetAtt:
                - ESLogGroup
                - Arn
```

but I get the error 

`Value of property LogPublishingOptions must be an object with String (or simple type) properties`

I have tried other ways to do this

```
     LogPublishingOptions: 
        ES_APPLICATION_LOGS: 
            Enabled: true
            CloudWatchLogGroupArn: hardcodedArn
```

```
     LogPublishingOptions: 
        ES_APPLICATION_LOGS: "{CloudWatchLogGroupArn=hardcodedArn,Enabled=true}"
```

```
     LogPublishingOptions: 
        ES_APPLICATION_LOGS.Enabled: true
        ES_APPLICATION_LOGS.CloudWatchLogGroupArn:
              Fn::GetAtt:
                - ESLogGroup
                - Arn
```

```
     LogPublishingOptions: 
        - Key:  ES_APPLICATION_LOGS
           Value: 
               Enabled: true
               CloudWatchLogGroupArn:
                  Fn::GetAtt:
                    - ESLogGroup
                    - Arn

```

and I keep getting the same error each time.  What is the correct syntax for this?  I noticed it was only added recently.

Thanks
