### ISSUE TITLE
AWS::RDS::DBCluster fails to modify existing Serverless cluster when updating any parameters

### ISSUE THREAD

**Issue by GenPage** [aws-cloudformation/aws-cloudformation-coverage-roadmap#396]
#### 1. Title 
AWS::RDS::DBCluster fails to modify existing Serverless cluster when updating any parameters

#### 2. Scope of request 
AWS::Cloudformation::Stack - can modify Aurora Serverless cluster, but not via CloudFormation Stack

#### 3. Expected behavior
when updated/modified via CF stack, AWS::RDS::DBCluster doesn't try to modify the following values in the CF stack if they have not changed.
- Port
- PreferredBackupWindow
- PreferredMaintenanceWindow

#### 4. Suggest specific test cases
1.  Create a Aurora Serverless Cluster via CF Stack that defines one of the vaules above. (let use Preffered Maintenance Window for now)
2. Modify the Aurora Cluster via the stack (update MaxCapacity for example
3. Get UpdateRollback with following error:
```
You currently can't modify MaintenanceWindow with Aurora Serverless. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 31efe4ae-538a-416e-9a6f-cf1210c7ba6c)
```

#### 5. Helpful Links to speed up research and evaluation
Mentioned on forums here: https://forums.aws.amazon.com/thread.jspa?messageID=911260

#### 6. Category (required) - Will help with tagging and be easier to find by other users to +1
DB (Aurora Serverless)
Management (CloudFormation)

#### 7. Any additional context (optional)
I have opened a Enterprise support ticket and the support agent confirmed this is a bug and tracked on the internal bug tracker.

I haven't tested this with other Aurora engine modes, but it does seem like it would affect any Aurora cluster.

**Comment by andrewthetechie** [comment]
A fix for this would be to remove Port, PreferredBackupWindow, and PreferredMaintenanceWindow from the template when setting up Aurora Serverless

**Comment by PatMyron** [comment]
Reproduction templates:
```yaml
Resources:
  Resource:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      PreferredMaintenanceWindow: sun:01:00-sun:03:00
      MasterUserPassword: abcabcabc
      MasterUsername: abc
      EngineMode: serverless
```


```yaml
Resources:
  Resource:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      PreferredMaintenanceWindow: sun:01:00-sun:03:00
      MasterUserPassword: abcabcabc
      MasterUsername: abc
      EngineMode: serverless
      EnableCloudwatchLogsExports:
        - error
```

---

[Someone reported workarounds of commenting out `PreferredMaintenanceWindow`](https://stackoverflow.com/questions/57411251/you-currently-cant-modify-maintenancewindow-with-aurora-serverless-error-whil#comment101389297_57411251)

**Comment by matthewhegarty** [comment]
I attempted to enable `EnableIAMDatabaseAuthentication` in CFN via an `update-stack` command and got:

```
You currently can't modify IAM Authentication with Aurora Serverless. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: a36df001-63d3-4ef7-b2c5-xxxxx)
``

**Comment by hong823** [comment]
This also happens when trying to update an existing CloudFormation with `PreferredBackupWindow` value.

`You currently can't modify BackupWindow with Aurora Serverless. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: ...`

Commenting that property out will on upcoming CloudFormation helps solved it too as suggested by @PatMyron.

My CloudFormation template now looks like this:

```
AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      DatabaseName: mydatabase
      EngineMode: serverless
      EngineVersion: 10.7
      # PreferredBackupWindow: 01:00-02:00
      # PreferredMaintenanceWindow: sun:02:00-sun:03:00
      ......
```
