### ISSUE TITLE
AWS::EC2::VPCEndPointService, AWS::EC2::VPCEndpointConnectionNotification GovCloud

### ISSUE THREAD

**Issue by bgardner-noggin** [aws-cloudformation/aws-cloudformation-coverage-roadmap#400]
## 2. Scope of request 
Should be able to use AWS::EC2::VPCEndpointService and AWS::EC2::VPCEndpointConnectionNotification in GovCloud regions

## 3. Expected behavior

In GovCloud, using either of these resource types errors with "resource type not available"

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by PatMyron** [comment]
minimal [`AWS::EC2::VPCEndpointService`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html) template for testing:
```yaml
Resources:
  VPCEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      NetworkLoadBalancerArns:
        - !Ref LoadBalancer
  LoadBalancer:
    DependsOn: VPCGatewayAttachment
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Subnets:
        - !Ref Subnet
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/16
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
```
