### ISSUE TITLE
AWS::SecretsManager::Secret-DeletionPolicy

### ISSUE THREAD

**Issue by AknEp** [aws-cloudformation/aws-cloudformation-coverage-roadmap#405]
I want to keep secret value after stack deletion, similar to other almost all resources can.

## 2. Scope of request 

AWS::SecretsManager::Secret-DeletionPolicy DOES NOT supports DeletionPolicy.

It would be a `new option for an existing attribute is desired` type of request.

## 3. Expected behavior

I expect `AWS::SecretsManager::Secret` to be exists after stack deletion, s3::Bucket or other many resources as is.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

8. Security (IAM, KMS...)

**Comment by PatMyron** [comment]
Creating and deleting a stack with this template works as desired in `us-east-1`:

```yaml
Resources:
  Resource:
    DeletionPolicy: Retain
    Type: AWS::SecretsManager::Secret
```
