### ISSUE TITLE
AWS::XRay::SamplingRule - New Resource

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/aws-cloudformation-coverage-roadmap#41]
Title -> AWS::XRay::SamplingRule
Scope of request -> Manages X-Ray sampling rule resources
Expected behavior -> Create, Update and Delete X-Ray sampling rules
Test case recommendation (optional) ->
```
SamplingRule:
    Type: "AWS::XRay::SamplingRule"
    Properties:
        RuleName: "mySamplingRule"
        ResourceArn: "*"
        Priority: 10
        FixedRate: 0.05
        ReservoirSize: 1
        ServiceName: "*"
        ServiceType: "*"
        Host: "*"
        HttpMethod: "*"
        UrlPath: "*"
        Version: 1
        Attributes:
          - Key: "Origin"
            Value: "example.com"
```
Links to existing API doc (optional) -> https://docs.aws.amazon.com/xray/latest/api/API_CreateSamplingRule.html
Category tag (optional) -> Developer Tools, X-Ray
