### ISSUE TITLE
AWS::ApiGatewayV2::Integration.ConnectionType VPC_LINK

### ISSUE THREAD

**Issue by TheSkorm** [aws-cloudformation/aws-cloudformation-coverage-roadmap#411]
AWS::ApiGatewayV2::Integration.ConnectionType doesn't support type VPC_LINK even though API supports it. 

Currently I can use boto3 to call apigatewayv2.update_integration and target ConnectionId to the AWS::ApiGateway::VpcLink reference. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewayv2.html#ApiGatewayV2.Client.update_integration

At the moment working around the issue using cf-shim
```
    VPCLinkAttachForConnect: # AWS Currently doesn't support setting VPC Link for API Gateway V2 through CloudFormation so we use CF Shim to use the api
        Type: Custom::CFShim
        Properties:
            ServiceToken: !GetAtt ShimLambda.Arn
            Service: "apigatewayv2"
            Create: "update_integration" 
            PhysicalResourceId: "ConnectionId" 
            CreateData: 
                ApiId: !Ref ApiGateway
                IntegrationId: !Ref ApiGatewayConnectIntegration
                ConnectionType: VPC_LINK
                ConnectionId: !Ref VPCLink
```
