### ISSUE TITLE
Fn::Transform - ability to interpolate template parameters in macro name

### ISSUE THREAD

**Issue by bjorg** [aws-cloudformation/aws-cloudformation-coverage-roadmap#416]
## 2. Scope of request 
CloudFormation macros are executed before intrinsic functions, which makes it impossible to use `Fn::Sub` or `Fn::Join` to build a macro name dynamically. However, macros have access to the template parameters. As such, an enhancement would be to allow macro names to be built using interpolation (similar to `Fn::Sub`) with template parameter references.

Note that there is currently no work-around for deployment environment specific macros other than to hard-code these names into the CloudFormation template or rewriting the template as pre-deployment step.

A specific use case would be to prefix a macro name with the stage it belongs to (e..g 'test-` or `prod-`). By using string interpolation, the construction of the final macro name is flexible based on established deployment practices.

#### Fn::Transform JSON Example
```json
{
  "Fn::Transform": {
    "Name": "${Stage}-MyMacro", 
    "Parmeters": { }
  }
}
```

#### !Tranform YAML Example
```yaml
!Transform:
  Name: ${Stage}-MyMacro
  Parameters: { }
```

#### Template Example
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: ${Stage}-MyGlobalMacro
Parameters:
  Stage:
    Type: String
Resources: { }
```

## 3. Expected behavior
When detecting the string interpolation notation (i.e. `${...}`) in a macro name, attempt to substitute the template parameters to build the final macro name. If a parameter is missing or the string is malformed, error out with invalid macro name message.

## 4. Suggest specific test cases
(see examples above)

## 5. Helpful Links to speed up research and evaluation
* [Fn::Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-transform.html)

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Management (CloudTrail, Config...)
