### ISSUE TITLE
AWS::ECS::TaskDefinition-Volumes-EfsVolumeConfiguration

### ISSUE THREAD

**Issue by Trane9991** [aws-cloudformation/aws-cloudformation-coverage-roadmap#418]
AWS::ECS::TaskDefinition-Volumes currently supports `dockerVolumeConfiguration` but not the `EfsVolumeConfiguration`

[Feature announcement](https://aws.amazon.com/about-aws/whats-new/2020/01/amazon-ecs-preview-support-for-efs-file-systems-now-available/)
[Tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_efs.html)
[Docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

Category: Compute

**Comment by autarchprinceps** [comment]
Now also supported for Fargate: https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/ so having this in CloudFormation would be really important.

**Comment by Trane9991** [comment]
[Amazon ECS and AWS Fargate support for Amazon EFS File Systems now generally available](https://aws.amazon.com/ru/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/)

**Comment by jupeter** [comment]
Conform, EfsVolumeConfiguration is not supported by CloudFormation. 

Error on Stack update: 
> Encountered unsupported property EfsVolumeConfiguration

Sample configuration: 
```
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
# ...
      Volumes:
        - Name: data
          EfsVolumeConfiguration:
            FileSystemId: !Ref EfsResource
```
Additionally this function need to be documented here: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-volumes.html

Just for the record, EfsVolumeConfiguration is already supported by TaskDefinition API: 
 - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html
 -https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_EFSVolumeConfiguration.html
