### ISSUE TITLE
AWS::Lambda::Permission-SourceArn Allow `*` regions in SourceArn

### ISSUE THREAD

**Issue by txase** [aws-cloudformation/aws-cloudformation-coverage-roadmap#431]
## 1. Title 
AWS::Lambda::Permission-SourceArn

## 2. Scope of request 
AWS::Lambda::Permission SourceArn property is used to specify which resources, like SNS topics, are allowed to invoke the referenced Lambda Function. The SourceArn is put in a condition in the Lambda permission like:

```JSON
{
  "Sid": "<Generated Sid>",
  "Effect": "Allow",
  "Principal": {
    "Service": "sns.amazonaws.com"
  },
  "Action": "lambda:InvokeFunction",
  "Resource": "<Lambda Function Arn>",
  "Condition": {
    "ArnLike": {
      "AWS:SourceArn": "<SourceArn property value>"
    }
  }
}
```

This syntax allows for wildcards in the region attribute of the SourceArn, but CloudFormation doesn't allow the region to be `*`. The property validation checking simply needs to be loosened to allow for `*` resources.

This is especially helpful for SNS topics in many regions to be subscribed to a single Lambda Function in a central region.
Whether a new API call requires a new attribute, or a new feature is supported and needs to be added to CloudFormation.

## 3. Expected behavior
A resource like the following should succeed in placing a region-agnostic permission on a Lambda Function:

```yaml
Resources:
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyFunction
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:*:${AWS::AccountId}:my-cross-region-topic
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
1. Compute (EC2, ECS, EKS, Lambda...)
