### ISSUE TITLE
AWS::S3::Bucket - BucketName accesible via Fn::GetAtt

### ISSUE THREAD

**Issue by akunszt** [aws-cloudformation/aws-cloudformation-coverage-roadmap#471]
## 1. Title 
AWS::S3::Bucket - BucketName accesible via Fn::GetAtt

## 2. Scope of request 
Make the BucketName accessible using Fn::GetAtt on an AWS::S3::Bucket resource.

## 3. Expected behavior
Get back the bucket's name created for the AWS::S3::Bucket resource, e.g. `mycompany-mybucket`.

## 4. Suggest specific test cases
N/A

## 5. Helpful Links to speed up research and evaluation
N/A

## 6. Category
Storage

## 7. Any additional context
We're using a 3rd party Python Lambda - maybe provided by AWS itself, I don't know - which expects an S3 bucket name - not an ARN, not an URL, not a DomainName. Currently we're generating the bucket's name using the environmental information like this:
```
"Fn::Sub": "mycompany-${AWS::StackName}-${AParameter}-${AWS::Region}"
```
It would be easier if we can fetch the bucket name from the S3 resource itself and we don't have to copy/paste that "rule" everywhere where we want to use the bucket's name.
```
"Fn::GetAtt": [ "MyBucket", "BucketName" ]
```
It's shorter and if the bucket name generation changes we don't have to search and replace every occurences. I know I can solve this with Fn::GetAtt.Arn, Fn::Split and Fn::Select but thats even complicated and silently assumes that the number of double colons (:) doesn't change in the ARN.

**Comment by benkehoe** [comment]
The bucket name available; it's returned by `Fn::Ref`, rather than by `Fn::GetAtt`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#aws-properties-s3-bucket-return-values

**Comment by akunszt** [comment]
Hmmm... That's not the resource name? If it's really the BucketName, then it's okay, just the documentation tricked me.

**Comment by benkehoe** [comment]
In CloudFormation, for every resource, you have a logical resource id and a physical resource id.  The logical resource id is the name for that resource within a stack. The physical resource id is a type-specific unique identifier. It's usually either the name or the ARN of the resource, it (sadly) varies by resource type. In the case of `AWS::S3::Bucket`, it's the name (i.e., the bucket name). Similarly, for [`AWS::DynamoDB::Table`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#aws-resource-dynamodb-table-return-values), it's the table name. But for [`AWS::ECS::Service`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#aws-resource-ecs-service-return-values), `Fn::Ref` returns the ARN, and `Name` is an attribute. This can be frustratingly inconsistent, but [here's a cheatsheet for it](https://theburningmonk.com/cloudformation-ref-and-getatt-cheatsheet/).

So if you had this resource:
```
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      ...
```
the logical id of the resource is `MyBucket`. Creating the stack creates a bucket resource with a name something like `mystack-mybucket-kdwwxmddtr2g`. The physical resource id of the `MyBucket` resource is then `mystack-mybucket-kdwwxmddtr2g`. `Fn::Ref` returns the physical resource id, so `mystack-mybucket-kdwwxmddtr2g`. And `Fn::GetAtt MyBucket.Arn` returns `aws:s3:::mystack-mybucket-kdwwxmddtr2g`

**Comment by benkehoe** [comment]
I submitted feedback on that docs page that they should make it explicit that the value of `!Ref` is the bucket name.

**Comment by benkehoe** [comment]
Also note that when you are viewing a stack in the console, the "Resources" tab shows you a table with both logical id and physical id. With the CLI, this is [`aws cloudformation describe-stack-resources`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stack-resources.html)

**Comment by akunszt** [comment]
Thanks. When I use !Ref then I usually get back the Logical Id for other kind of resources - or the ARN as you wrote - so that's what confused me in this case. I think too that it's worth to emphasize this behaviour in the docs more clearly.

**Comment by benkehoe** [comment]
`Fn::Ref` always returns the physical resource id, for all resources. The logical id only exists inside the template, and you already know the value of it inside the template: it's the _input_ to `Fn::Ref` and `Fn::GetAtt`. So for most CloudFormation resource types, when you want the resource name (which is the bucket name for `AWS::S3::Bucket`, the table name for `AWS::DynamoDB::Table`, the function name for `AWS::Lambda::Function`, ...), you're going to use `Fn::Ref`.

**Comment by JoshMcCullough** [comment]
The follow results in the value `Bucket` being set as the env var `BUCKET` rather than e.g. `dev-some-data`:

```yaml
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${TargetEnvironment}-some-data

  Function:
    Type: AWS::Serverless::Function
    Properties:
      # ...
      Environment:
        Variables:
          BUCKET: !Ref Bucket
```

**Comment by DeftlyNotBru** [comment]
I found myself in a situation that required a reference to `BucketName`. While `Fn::Ref` does properly return the bucket name, this is not evident, and could be improved.

Current documentation for `Fn::Ref` states
> When you specify a resource's logical name, it returns a value that you can typically use to refer to that resource, such as a [physical ID](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html)

Here, “a value that you can typically use to refer to that resource” is ambiguous, and in my case left me no choice other than just assuming it resolves to `BucketName` in this particular scenario. To resolve this, I suggest either
- Resolving the ambiguity in the documentation, being clearer about the circumstances where the name can be expected.
- Incorporating the capability of returning resources' names into `Fn::GetAtt`

To the best of my knowledge, the latter would be preferable for at least two reasons:
- `Fn::GetAtt` is intrinsically non-ambiguous. No one would expect `!GetAtt MyBucket.BucketName` (or `MyBucket.Properties.BucketName`?) to resolve to anything other than `MyBucket`'s `BucketName`
- Since `BucketName` is indeed an attribute of buckets, it would be consistent to be able to fetch it this way.

**Comment by benkehoe** [comment]
@DeftlyNotBru this a more general problem with CloudFormation resource inconsistency. Generally the physical resource id is either the name or the ARN, and the opposite (the ARN or the name) is usually available as an attribute, but it varies from resource to resource which one it is. The new registry-based resource provider model (that is, all the resources you can find open-source [here](https://github.com/aws-cloudformation/resource-providers-list)) does away with that, and both names and ARNs should be available as attributes. But it's up to the service teams, not CloudFormation, to migrate their resources to the new framework (it being a service team responsibility is what allows it to scale, meaning we get CFN support at launch more often).

I think the bigger question is, for quality-of-life issues like this on legacy resources, at what point should the CloudFormation team take on updating them because the service teams are taking too long? Keeping in mind this is traded off against all the other things we want CloudFormation to do.

**Comment by benkehoe** [comment]
@JoshMcCullough I'm not sure what's happening for you, but I can't replicate it. Here's a complete template that, for me, results in the correct bucket name being put into the function's environment variable:
```yaml
Transform: AWS::Serverless-2016-10-31
Parameters:
  TargetEnvironment:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${TargetEnvironment}-some-data

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          raise NotImplementedError
      Environment:
        Variables:
          BUCKET: !Ref Bucket
```
