### ISSUE TITLE
AWS::CloudFormation::ResourceVersion-Region-Allow private resource type to be available globally

### ISSUE THREAD

**Issue by eduardomourar** [aws-cloudformation/aws-cloudformation-coverage-roadmap#493]
## 2. Scope of request 
It would be nice to have the option to register a private resource provider for a particular AWS account and to **all regions**. This applies to AWS API itself so that we can have the same behavior across AWS CLI, CloudFormation template (when available), etc.

I would even argue that Resource Types should be global by default just like IAM resources.

## 3. Expected behavior
In Create/Update, we should have a property to set that resource type globally available.

## 4. Suggest specific test cases
One could try to use the following hypothetical template:

```yaml
Type: AWS::CloudFormation::ResourceVersion
Properties:
    ExecutionRoleArn: ...
    LoggingConfig: ...
    SchemaHandlerPackage: ...
    TypeName: Organization::Service::Resource
    Visibility: PRIVATE  # Even if visibility could be set to public/private in the future
    Global: true
```

## 6. Category

Management (CloudTrail, Config...)
