### ISSUE TITLE
AWS::Lambda::Function doesnt support java8 runtime for ZipFile

### ISSUE THREAD

**Issue by dnmange** [aws-cloudformation/aws-cloudformation-coverage-roadmap#495]
## Issue:
AWS::Lambda::Function doesn't support java8 runtime for ZipFile.

## Steps to Reproduce:
1. create a cloud formation template with resource type as AWS::Lambda::Function.
2. include runtime as java8, and Code property with ZipFile.
3. deploy the template

## Template Sample:

```
ResourceName:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Ref path_to_zip_file
      Runtime: java8
```
## Error:
ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7.
