### ISSUE TITLE
AWS::IoT::ProvisioningTemplate (new resource)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/aws-cloudformation-coverage-roadmap#512]
## AWS::IoT::ProvisioningTemplate (new resource)

2. Scope of request -> Allow a way to create, update and delete IoT provisioning templates

6. Category tag (optional) -> Other

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

```yaml
Resources:
  ProvisioningTemplate:
    Type: AWS::IoT::ProvisioningTemplate
    Properties:
      ProvisioningRoleArn: !GetAtt Role.Arn
      TemplateBody: !Sub "{\"Parameters\":{\"SerialNumber\":{\"Type\":\"String\"}},\"Resources\":{\"certificate\":{\"Properties\":{\"CertificateId\":{\"Ref\":\"AWS::IoT::Certificate::Id\"},\"Status\":\"Active\"},\"Type\":\"AWS::IoT::Certificate\"},\"policy\":{\"Properties\":{\"PolicyDocument\":\"{\\n  \\\"Version\\\": \\\"2012-10-17\\\",\\n  \\\"Statement\\\": [\\n    {\\n      \\\"Effect\\\": \\\"Deny\\\",\\n      \\\"Action\\\": \\\"iot:*\\\",\\n      \\\"Resource\\\": \\\"arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/sample-topic\\\"\\n    }\\n  ]\\n}\"},\"Type\":\"AWS::IoT::Policy\"}}}"
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
```
