### ISSUE TITLE
AWS::CertificateManager::Certificate-DomainValidationOption-HostedZoneName

### ISSUE THREAD

**Issue by mbarneyjr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#521]
## 1. Title

AWS::CertificateManager::Certificate-DomainValidationOption-HostedZoneName

## 2. Scope of request

I recently saw CloudFormation support for creating and validating `AWS::CertificateManager::Certificate` resources without the need for custom resources/manual actions through the addition of the `AWS::CertificateManager::Certificate.DomainValidationOption.HostedZoneId` property (many thanks, this is amazing!).

## 3. Expected behavior

I would like to see support for a `HostedZoneName` property, similar to what we see with the `AWS::Route53::RecordSet` resource ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-hostedzonename)).

> When you create a stack using an AWS::Route53::RecordSet that specifies HostedZoneName, AWS CloudFormation attempts to find a hosted zone whose name matches the HostedZoneName. If AWS CloudFormation cannot find a hosted zone with a matching domain name, or if there is more than one hosted zone with the specified domain name, AWS CloudFormation will not create the stack.

## 4. Suggest specific test cases

An example would look like this:

```yml
  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: domain.com
      SubjectAlternativeNames:
        - *.domain.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: domain.com
          HostedZoneName: domain.com
```

## 5. Helpful Links to speed up research and evaluation.

`AWS::Route53::RecordSet.HostedZoneName` docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-hostedzonename

`AWS::CertificateManager::Certificate.DomainValidationOption.HostedZoneId` docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-certificatemanager-certificate-domainvalidationoption.html#cfn-certificatemanager-certificate-domainvalidationoption-hostedzoneid
