### ISSUE TITLE
AWS::EC2::FlowLog Tags

### ISSUE THREAD

**Issue by mbikas** [aws-cloudformation/aws-cloudformation-coverage-roadmap#528]
## 1. Title 
CloudFormation does not support adding tags to VPC FlowLog `AWS::EC2::FlowLog`.

## 2. Scope of request 
It is now possible to [add tags to VPC FlowLogs](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-vpc-flow-logs-support-resource-tagging-tag-on-create/) via console and boto3 API. However, adding tags to FlowLogs via [cloudformation is not yet supported.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-flowlog.html). Would like to have that cloudformation support added.

## 3. Expected behavior

Add a new parameter to `AWS::EC2::FlowLog` Resource to add Tags.
Example:
```
FlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      .....
      Tags:
          - Key: ...
            Value: ...
```

## 4. Suggest specific test cases
```
FlowLogsS3:
    Type: AWS::EC2::FlowLog
    Properties:
      LogDestinationType: s3
      ResourceId: vpc_id
      ResourceType: VPC
      TrafficType: ALL
      LogDestination: bucket_name
     Tags:
         - Key: key1
            Value: value1
```

## 5. Helpful Links to speed up research and evaluation
- We can add tags to VPC FlowLogs via console: https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-vpc-flow-logs-support-resource-tagging-tag-on-create
- It would be great if we can do the same via cloudformation

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2)
2. Networking & Content (VPC, FlowLogs)

## 7. Any additional context (optional)
Currently fails with:
<img width="1201" alt="Screen Shot 2020-06-16 at 1 15 39 PM" src="https://user-images.githubusercontent.com/7716634/84824615-139a5e00-afd5-11ea-829d-e0ecb781395b.png">
