### ISSUE TITLE
AWS::DirectoryService::MicrosoftAD - Remove Password and Initialize with a Random Value

### ISSUE THREAD

**Issue by ambsw-technology** [aws-cloudformation/aws-cloudformation-coverage-roadmap#542]
The current situation is a disaster:

 - I'm forced to provide a password
 - I cannot rotate the password through CloudFormation without triggering replacement
 - If I rotate the password in the UI (as instructed), I have to keep track of the original password in the event I need to make **any** other update to the stack (otherwise I trigger a replacement).  Where am I supposed to keep that password?

I believe this attribute should be deprecated and removed.  Directory Services should be initialized with a random password and users should update the password through the UI.

**Comment by ambsw-technology** [comment]
FWIW I just stumbled upon `UsePreviousValue` which addresses bullet 3 for people who are "in the know".  For everyone else it remains a security issue and the parameter is virtually useless otherwise.  If you want/need to expose programmatic access, it'd be far better to create a CF resource with an "AdminUser" flag that would permit rotation without replacement (i.e. the change password API endpoint that already exists).

**Comment by nbmha1** [comment]
Think this would be better if Secrets Manager <--> Directory Service integration allowed native rotating of the admin password?

**Comment by ambsw-technology** [comment]
@mbnha1 This repo is for CloudFormation suggestions.  I've proposed removing the ability to configure passwords through the current resource.  If someone wants a CloudFormation resource that could manage this password, I've provided the best alternative I can come up with.  The question isn't so much better/worse than alternatives but (1) if it belongs in CloudFormation and (2) where.

**Comment by nbmha1** [comment]
> @nbmha1 This repo is for CloudFormation suggestions. I've proposed removing the ability to configure passwords through the current resource. If someone wants a CloudFormation resource that could manage this password, I've provided the best alternative I can come up with. The question (here at least) isn't so much better/worse than alternatives but (1) if it belongs in CloudFormation and (2) where.

Understood.  The way we achieved this was using Secrets Manager to create an initial random password in the end.  Can then be rotated using a Lambda.  It's a bit clunky, but works...

```yaml
  AWSManagedADSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Secret used for provisioning Managed AD'
      GenerateSecretString:
        PasswordLength: 24

  AWSManagedAD:
    DependsOn: AWSManagedADSecret
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Edition: Enterprise
      CreateAlias: False
      EnableSso: False
      Name: mydomain.com
      Password: !Sub '{{resolve:secretsmanager:${AWSManagedADSecret}}}'
      ShortName: mydomain
      VpcSettings:
        SubnetIds: 
        - !Ref PrivateSubnet0
        - !Ref PrivateSubnet1
        VpcId: !Ref VPC
```
