### ISSUE TITLE
AWS::EC2::Instance-BlockDeviceMappings - drift detection - handle root volume from AMI which is not defined CFN template

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/aws-cloudformation-coverage-roadmap#543]
1.	Title
-> AWS::EC2::Instance-BlockDeviceMappings - drift detection - handle root volume from AMI which is not defined CFN template
2.	Defining the Problem
-> Once I'm creating a EC2 instance from AMI and doing **no** defintion of the root-volume via AWS::EC2::Instance-BlockDeviceMappings, I'm getting a drift in CFN, e.g.: If the block device (e.g. "/dev/xvda") is the root volume and since this was not specified in the "BlockDeviceMappings" property section, the "AWS::EC2::Instance" resource is showing up as "Change: ADD" and so this appears to be a false positive.
3.	Steps to recreate the issue:
* launching a CloudFormation stack in the EU-Central-1 region using following sample template:
```
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-07cda0db070313c52
      InstanceType: m5.large
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: '10'
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: '5'
```
* run the CFN drift detection and check the drift results of your stack. You can see ADD on the Drift Details (which is the false positive).

4.	Expected behavior
-> CloudFormation drift detection is able handle such cases.

5.	Category tag
-> Compute

6. Additional context
-> There should be something like a Warining message from CFN drift detection in order to understand that the root volume has been created automatically and now there is a "false positive" while comparing resources and template via drift detection.

**Comment by rgoltz** [comment]
I just tested this in us-east-1 (June 2026) with a template that defines an additional volume (/dev/sdb) but not the root volume. Drift Detection now shows the root volume in the actual state but correctly reports the stack as IN_SYNC. This issue appears to be resolved.

Here are the details - Test-Template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Minimal repro for root volume ADD false positive drift (#543)"

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: 10
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: drift-bug-543-root-volume-test
```

Result of Drift Detection:
<img width="1314" height="865" alt="Image" src="https://github.com/user-attachments/assets/f93f0442-d5c2-461f-8389-b6be434f95dc" />

I'll go ahead and close this issue :-) [6 years later ;-)]
