### ISSUE TITLE
AWS::CloudFormation::Stack - Region

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/aws-cloudformation-coverage-roadmap#562]
## 2. Scope of request 
Currently certain resources (e.g. ACM for CloudFront) require it is being deploy from within us-east-1. Or if i want a multi region codepipeline, each region also need bucket and kms...etc

I wonder can the multi region deployment simplify into a single nested stack and using it to refrence via the output of each nested stack.

e.g.
main root stack - ap-southeast-1
|- child stack - us-east-1
|- child stack - ap-southeast-1 use us-east-1's stack output as parameter

## 3. Expected behavior

In Create: it create a stack in target region
In Update: it update eh stack in target region
In Delete: it delete the stack in target region
Can mix multi region in one stack

## 4. Suggest specific test cases

```
Resources:
  CognitoACM:
    Type: AWS::CloudFormation::Stack
    Properties:
      Region: us-east-1
      Parameters:
        FDQN: auth.my-example.com
      TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/my-bucket/acm-cert.yaml'

  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      Region: ap-southeast-2
      Parameters:
        FQDN: auth.my-example.com
        AcmArn: !GetAtt 'ACMCert.Outputs.AcmArn'
      TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/my-bucket/cognito.yaml'

  MyAPIAcm:
    Type: AWS::CloudFormation::Stack
    Properties:
      Region: ap-southeast-2
      Parameters:
        FDQN: api.my-example.com
      TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/my-bucket/acm-cert.yaml'

  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      Region: ap-southeast-2
      Parameters:
        FQDN: api.my-example.com
        AcmArn: !GetAtt 'MyAPIAcm.Outputs.AcmArn'
      TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/my-bucket/apigateway.yaml'
```

## 5. Helpful Links to speed up research and evaluation

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/546
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/523
https://github.com/aws/aws-cdk/pull/8552
