### ISSUE TITLE
Hash Parameter Type

### ISSUE THREAD

**Issue by josb** [aws-cloudformation/aws-cloudformation-coverage-roadmap#575]
Given the 60 parameter template limit, structured parameters are a way to overcome this limitation. Example:

```
Parameters:
  LogGroupInfo:
    Type: Hash

...

Resources
...

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !GetAtt LogGroupInfo.Name
      RetentionInDays: !GetAtt LogGroupInfo.RetentionInDays

...
```

**Comment by PatMyron** [comment]
Would simply [raising the parameter limit](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/360) be better to avoid this workaround?
Because raising that limit is currently being investigated

**Comment by benkehoe** [comment]
I don't see this as a workaround; resources have structured parameters, and with nested stacks, stacks can be resources, so they should _also_ have structured parameters.

**Comment by josb** [comment]
Additionally, a Hash parameter type would help organize the stack parameter space. Traditionally, the example above would be implemented using two parameters, and some form of parameter prefix convention would be used to organize the names to indicate that they are related to the same resource. This imposes additional cognitive burden on humans, especially when many parameters are present. The same issue applies to outputs - instead of multiple related outputs, a single structured output could be used.

**Comment by PatMyron** [comment]
Got it. There's also [`AWS::CloudFormation::Interface`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html) which can help organize stack parameters a bit if using the console to input parameter values if that helps your use-case at all

**Comment by josb** [comment]
I'm aware of `AWS::CloudFormation::Interface`, but our use case has hundreds of CloudFormation stacks per deployment and is largely driven by extensive custom automation code. And because we are running into the 60-parameter limit, we had to resort to using parameter stacks just for the purpose of working around that limit. We do use the CloudFormation console, but mostly for debugging. For reasons stated above, with 700+ parameters per deployment, a Hash-type parameter would help us organize this better.

**Comment by Ricapar** [comment]
I think raising the parameter limit would certainly be something that would help in @josb's use case, but I would say that even without that scenario the overall CloudFormation developer community stands to benefit greatly from a hash/dictionary parameter type.

As an example, for a stack that perhaps creates two `AWS::EC2::Instances`, quite often I find myself generating parameters like this:

* Instance1Type
* Instance1VolumeSize
* Instance1SecurityGroup
* Instance2Type
* Instance2VolumeSize
* Instance2SecurityGroup

And if I suddenly need to make a 3rd instance as part of the stack or perhaps need a 4th parameter then that suddenly adds a lot more parameters.

With a hash/dict parameter type, even though I'd be passing the same amount of information, it would be a whole lot cleaner and easier to read and understand.

**Comment by jamby1100** [comment]
A workaround that has worked for me is using the [PyPlate CloudFormation macro](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/PyPlate/python.yaml). Create the macro first by creating a CF stack using that template. Then, in your template you can reference Python code to do the trick.

```yml
Transform: [PyPlate]
Parameters:
  AutoScalingContainerCountRange:
    Description: CONDITIONAL - The min and max number of containers
    Type: CommaDelimitedList
    Default: MinCapacity=2,MaxCapacity=5
```

```yml
Resources:
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: |
        #!PyPlate
        autoscale_range_dict = {}
        for alarm_param in params['AutoScalingContainerCountRange']:
          condition,value = alarm_param.split('=')
          autoscale_range_dict[condition] = value
        output = int(autoscale_range_dict['MinCapacity'])
```

This is not the most elegant solution since I had to use a macro. But it allows me to create key-value pairs like `MinCapacity=2,MaxCapacity=5`. I still support this feature request though! Adding a "Hash" parameter would make my templates cleaner since I don't have to add Python code inside my templates.

How about you guys, how did you work around this?
