### ISSUE TITLE
AWS::Cognito::UserPoolDomain

### ISSUE THREAD

**Issue by dehli** [aws-cloudformation/aws-cloudformation-coverage-roadmap#58]
## Scope of request 

Currently `AWS::Cognito::UserPool` doesn't support having a domain name. This resource should support either a domain prefix or using your own domain (but not both).

![image](https://user-images.githubusercontent.com/5856011/62242707-be982e00-b3a9-11e9-9825-7674ccc19864.png)

```
PrefixDomainName:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref UserPool
    DomainPrefix: "my-custom-prefix"

# OR

CustomDomainName:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref UserPool
    DomainName: "auth.example.com"
    CertificateArn: !Ref Certificate
```

### Outputs

- PrefixDomainName
  - `Url`: `https://my-custom-prefix.auth.${AWS::Region}.amazoncognito.com`
- CustomDomainName
  - `Url`: `https://auth.example.com`
  - `CloudfrontUrl`: `https://d1234567890.cloudfront.net`

## Suggest specific test cases

- not passing in `UserPoolId` should result in a failure
- passing in a `DomainName` with a protocol should result in a failure
- passing in a `DomainName` without `CertificateArn` should result in a failure
- passing in both `DomainPrefix` and `DomainName` should result in a failure
- passing in a `DomainPrefix` that is already taken should result in a failure

## Category

Category: Security, Identity, & Compliance

**Comment by andreaswittig** [comment]
In case you are wondering wether Terraform does support user pool domains already: https://www.terraform.io/docs/providers/aws/r/cognito_user_pool_domain.html :)

**Comment by dehli** [comment]
It would be cool if the resource would also support not passing in a prefix. In that case, a unique prefix would be assigned similar to how S3 bucket names are assigned. 

```
RandomDomainName:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref UserPool
```

**Comment by dehli** [comment]
Looks like this has been addressed with [AWS::Cognito::UserPoolDomain](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooldomain.html) 👍  

I still think it will be great to expose a `Url` output and to allow for the domain name to be randomly assigned but this resource is great! Thanks! 

Not sure if I should close this or wait until it's added to the project board. Cheers!

**Comment by Nr18** [comment]
I am missing the return value for the CloudFront target so that you could create a DNS record in the same template so that you could do this:

```yaml
  DNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: mydomain.com.
      Name: myuserpool.mydomain.com.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt UserPoolDomain.DomainName

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: myuserpool.mydomain.com
      CustomDomainConfig:
        CertificateArn: !Ref CertificateArn
```

**Comment by grosscol** [comment]
@Nr18 I ran into this issue recently.  The workaround I used was to create a custom resource to hold the CloudFront Distribution of the UserPoolDomain and used a lambda to do the lookup since the describe-user-pool-domain api does what we want.

Demo stack here: https://gist.github.com/grosscol/3623d2c2affdd3b88ed4538537bb0850

**Comment by hackash** [comment]
Here is how you do it in 2023: 

 ```
UserPoolDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${MainDomainName}."
      Name: !Sub "auth.${MainDomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt UserPoolDomain.CloudFrontDistribution
        EvaluateTargetHealth: false
UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join [ ".", [ "auth", !Ref MainDomainName ] ]
      CustomDomainConfig:
        CertificateArn: !Ref MainDomainCertificateARN
```
