### ISSUE TITLE
AWS::XRay::Group - New Resource

### ISSUE THREAD

**Issue by Nr18** [aws-cloudformation/aws-cloudformation-coverage-roadmap#581]
## 1. AWS::XRay::Group

When you are developing with multiple people in 1 account on different feature branches it is useful to have an easy way to filter out all traces that you are not interested in at that moment. Deploying a group that contains a filter to only show components that are in the CloudFormation template is really useful. But also for production workloads, it helps if you just want to examine a specific area.

## 2. Scope of request 

Manages X-Ray Group resources so that you have an easy way of filtering traces in the trace list and service map.

#### In Create
It should create a Group
#### In Update
It should be possible to update the filter without a replacement when the name changes a recplacement  is done
#### In Delete
It should delete the resource

## 4. Suggest specific test cases

```
XRayGroup:
    Type: "AWS::XRay::Group"
    Properties:
        GroupName: "myXRayGroup"
        FilterExpression: "service(\"mydomain.com\") {fault OR error}"
```

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/cli/latest/reference/xray/create-group.html

## 6. Category (required)

Developer Tools, X-Ray
