### ISSUE TITLE
AWS::AppSync::GraphQLApi - return API domain output property

### ISSUE THREAD

**Issue by rafalwrzeszcz** [aws-cloudformation/aws-cloudformation-coverage-roadmap#582]
## 2. Scope of request 

`AWS::AppSync::GraphQLApi` should return a value of an assigned domain so it could be possible to set up **CloudFront** distribution origin.

## 4. Suggest specific test cases

```yaml
Outputs:
    ApiDomain:
        Value: !GetAtt "AppSyncApi.DomainName"
```

## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

11. Other (AppSync)
