### ISSUE TITLE
AWS::CloudFormation::Delay (new resource)

### ISSUE THREAD

**Issue by eduardomourar** [aws-cloudformation/aws-cloudformation-coverage-roadmap#589]
## 2. Scope of request

In order to solve issues such as throttling (#588) or other scenarios where you want to delay the the next resource in line for deployment, I would like to propose to create a new CloudFormation resource type. It should be very similar to `AWS::CloudFormation::WaitCondition`[1], except that we don't need to wait for an external process, only for a period the time.

## 3. Expected behavior

It should be available a property to receive the timeout. The value must be in ISO8601 duration format [2], in the form: `PT#H#M#S`, where each # is the number of hours, minutes, and seconds, respectively.

## 4. Suggest specific test cases

This is an example usage for this hypothetical resource type:

```yaml
  DomainName1:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: example.com
      CertificateArn: ...

  Delay:
    Type: AWS::CloudFormation::Delay
    Properties:
      Timeout: PT1M

  # This should only start after 1 minute has passed
  DomainName2:
    Type: AWS::ApiGateway::DomainName
    DependsOn: Delay
    Properties:
      DomainName: api.example.com
      CertificateArn: ...
```

## 6. Category

5. Management (CloudTrail, Config...)
