### ISSUE TITLE
Tagging of Dedicated Host

### ISSUE THREAD

**Issue by codypenta** [aws-cloudformation/aws-cloudformation-coverage-roadmap#598]
## Tag Support of Dedicated Host

Quick Sample Summary:
1. Title -> AWS::Service::Resource-Attribute-Existing Attribute

AWS::EC2::Host
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-host.html

2. Scope of request -> AWS::Service::ResourceType::TheResource-ExistingAttribute supports A and B today, but not new C feature.

AWS::EC2::Host does not support assigning tags via cloudformation today but the support exist.
https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-ec2-adds-support-for-tagging-dedicated-hosts-upon-allocation/

3. Expected behavior -> In Create, it should include this and this, like the console.  Also include tag creation, like the API allows.

```yaml
Type: AWS::EC2::Host
Properties: 
  AutoPlacement: String
  AvailabilityZone: String
  HostRecovery: String
  InstanceType: String
  Tags: 
    - Key: "keyname1"
      Value: "value1"
    - Key: "keyname2"
      Value: "value2"
```

Let me know if any additional info is needed or if there is a better way to approach this. Thanks!
