### ISSUE TITLE
AWS::ElasticSearch::Domain-ElasticsearchClusterConfig can't parameterize ZoneAwarenessEnabled & ZoneAwarenessConfig

### ISSUE THREAD

**Issue by atheri** [aws-cloudformation/aws-cloudformation-coverage-roadmap#601]
## 2. Scope of request
When defining ZoneAwarenessConfig it's required for ZoneAwarenessEnabled to be true, this makes it hard to parameterize ElasticSearch deployments for different environments. I haven't found a way for something like AWS::NoValue to be applied in the current structure either.
```
Resources:
  ElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        ZoneAwarenessEnabled: !FindInMap [ESConfig, !Ref EnvironmentParam, ZoneAwarenessEnabled]
        ZoneAwarenessConfig:
          AvailabilityZoneCount: !FindInMap [ESConfig, !Ref EnvironmentParam, AvailabilityZoneCount]
```
doesn't work if ZoneAwarenessEnabled=false, results in error
`ZoneAwarenessEnabled must be set to True to specify the ZoneAwarenessSettings`

## 3. Expected behavior
If ZoneAwarenessEnabled=false then ignore ZoneAwarenessConfig

## 4. Suggest specific test cases

- ZoneAwarenessEnabled
  - true
    - ZoneAwarenessConfig 
      - exists - use those settings
      - doesn't exist - use defaults
  - false
    - ZoneAwarenessConfig - ignore it

## 5. Helpful Links to speed up research and evaluation
api docs: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-datatypes-elasticsearchclusterconfig
## 6. Category
Analytics

**Comment by cmckni3** [comment]
Does using a condition for `ZoneAwarenessConfig` with `AWS::NoValue` for the `false` case work?

**Comment by atheri** [comment]
I had tried several versions with AWS::NoValue, but it seems the syntax had got the better of me. I was able to get it working with 
```
Resources:
  ElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        ZoneAwarenessEnabled: false
        ZoneAwarenessConfig:
          Fn::If:
            - ESZoneAwareness
            - AvailabilityZoneCount: 3
            - Ref: "AWS::NoValue"
```
I'm new to cloudformation, so I didn't realize there were different use cases for `Fn::If` and `!If`, and that an object could be returned from the `Fn::If`. Before that I was trying something like this, to no avail.
```
Resources:
  ElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        ZoneAwarenessEnabled: false
        ZoneAwarenessConfig:
          Fn::If:
            - ESZoneAwareness
            - ""
            - Ref: "AWS::NoValue"
          AvailabilityZoneCount: !If [ESZoneAwareness, "3", !Ref "AWS::NoValue"]
```

My apologies.
