### ISSUE TITLE
AWS::EC2::Route, AWS::EC2::EIP for Wavelength

### ISSUE THREAD

**Issue by ao-log** [aws-cloudformation/aws-cloudformation-coverage-roadmap#610]
####  In Create AWS::EC2::Route, it should include carrier-gateway-id, like the AWS CLI command.

```
aws ec2 --region $REGION create-route \
--route-table-id $WL_RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--carrier-gateway-id $CAGW_ID
```

#### In Create AWS::EC2::EIP, it should include network-border-group, like the AWS CLI command.

```
aws ec2 --region $REGION \
allocate-address \
--domain vpc \
--network-border-group $NBG \
--query 'AllocationId'
```

## 4. Suggest specific test cases
The following document shows the way to create VPC and EC2 instances on Wavelength.

[Deploying your first 5G enabled application with AWS Wavelength](https://aws.amazon.com/jp/blogs/compute/deploying-your-first-5g-enabled-application-with-aws-wavelength/)

Use case is to use CloudFormation when using Wavelength.

## 5. Helpful Links to speed up research and evaluation

The followin properties are supported now. carrier-gateway-id in AWS::EC2::Route, network-border-group in AWS::EC2::EIP are not supported. On the other hand, CreateRoute and AllocateAddress API are support this feature.

[AWS::EC2::Route](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html)
```
Type: AWS::EC2::Route
Properties: 
  DestinationCidrBlock: String
  DestinationIpv6CidrBlock: String
  EgressOnlyInternetGatewayId: String
  GatewayId: String
  InstanceId: String
  NatGatewayId: String
  NetworkInterfaceId: String
  RouteTableId: String
  TransitGatewayId: String
  VpcPeeringConnectionId: String
```

[CreateRoute](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html)
```
 CarrierGatewayId
    The ID of the carrier gateway.
    You can only use this option when the VPC contains a subnet which is associated with a Wavelength Zone.
    Type: String
    Required: No
```

[AWS::EC2::EIP](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html)
```
Type: AWS::EC2::EIP
Properties: 
  Domain: String
  InstanceId: String
  PublicIpv4Pool: String
  Tags: 
    - Tag
```

[AllocateAddress](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html)
```
 NetworkBorderGroup
    A unique set of Availability Zones, Local Zones, or Wavelength Zones from which AWS advertises IP addresses. Use this parameter to limit the IP address to this location. IP addresses cannot move between network border groups. 
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by FireballDWF** [comment]
CarrierGatewayId attribute now supported for ::Route, but NetworkBorderGroup still missing from ::EIP

**Comment by FireballDWF** [comment]
> CarrierGatewayId attribute now supported for ::Route, but NetworkBorderGroup still missing from ::EIP
NetworkBorderGroup is not longer missing from ::EIP per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html#cfn-ec2-eip-networkbordergroup

**Comment by xmik** [comment]
Hey, it's great that `AWS::EC2::EIP` now supports the property `NetworkBorderGroup`.
It would be even better if an example was added to the documentation on how to set the value of `NetworkBorderGroup`. Right now, the documentation describes it in this way:
```
A unique set of Availability Zones, Local Zones, or Wavelength Zones from which AWS advertises IP addresses. Use this parameter to limit the IP address to this location. IP addresses cannot move between network border groups.
```
but the type of the property is `String`, which confuses me.

The value that worked for me was:
```
MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc-identifier-here"
      NetworkBorderGroup: !Ref AWS::Region
``` 
Having it added to the documentation would have saved me some time.
