### ISSUE TITLE
Handle duplicates when defining SecurityGroupIngress as property of AWS::EC2::SecurityGroup

### ISSUE THREAD

**Issue by brachna9** [aws-cloudformation/aws-cloudformation-coverage-roadmap#612]
## 3. Expected behavior

If a duplicate entry is made in the SecurityGroupIngress property of "AWS::EC2::SecurityGroup" resource, CloudFormation should not show it as a drift. Also, the ingress rule should not be removed if only duplicate entry is removed from the ingress rules list.

Sample snippet to replicate -

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  TestSg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Test duplicate ingress
      VpcId: vpc-6efe0c14
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 172.24.186.0/23
          Description: EntryA 
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 172.24.186.0/23
          Description: EntryB (Duplicate)
```

Drift Result when this stack is created -
<img width="1318" alt="Screenshot 2020-08-21 at 10 02 21 AM" src="https://user-images.githubusercontent.com/45456696/90853808-d1a4e400-e398-11ea-831d-1314fde66d2e.png">

Drift Result when Duplicate ingress (EntryB) is removed in update -
<img width="1315" alt="Screenshot 2020-08-21 at 10 17 58 AM" src="https://user-images.githubusercontent.com/45456696/90853822-d9648880-e398-11ea-82dc-3551579a224d.png">

Category - Compute
