### ISSUE TITLE
AWS::ApiGateway::Stage-AutoDeploy

### ISSUE THREAD

**Issue by eduardomourar** [aws-cloudformation/aws-cloudformation-coverage-roadmap#623]
## 2. Scope of request 

The API Gateway v1 (REST) Stage resource should have a `AutoDeploy` attribute similar to the v2 (HTTP), where it can be specified whether updates to an API automatically trigger a new deployment [1].

## 3. Expected behavior

The same behavior as the attribute in v2 taking in to consideration that `DeploymentId` cannot be provided for this attribute to work and the default value should be `false`.

## 4. Suggest specific test cases

Then you could deploy the following CloudFormation template: 

```yaml
MyStage:
  Prod:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      RestApiId: !Ref MyRestApi
      AutoDeploy: true
```

## 6. Category

4.  Networking & Content (VPC, Route53, API GW,...)
