### ISSUE TITLE
Parameters - validation of CommaDelimitedList with AllowedValues

### ISSUE THREAD

**Issue by vtuhtan** [aws-cloudformation/aws-cloudformation-coverage-roadmap#627]
## 2. Scope of request 
Add support for CommaDelimitedList type parameter **with** AllowedValues constraint.

Sample: 
In this example I would like to use a CF template which defines CodeStar notification(s) rule as a parameter
```
NotificationEvents:
    Type: CommaDelimitedList
    Default: "codepipeline-pipeline-pipeline-execution-failed,codepipeline-pipeline-pipeline-execution-succeeded"
    AllowedValues:
      - codepipeline-pipeline-action-execution-succeeded
      - codepipeline-pipeline-action-execution-failed
      - codepipeline-pipeline-action-execution-canceled
      - codepipeline-pipeline-action-execution-started
      - codepipeline-pipeline-stage-execution-started
      - codepipeline-pipeline-stage-execution-succeeded
      - codepipeline-pipeline-stage-execution-resumed
      - codepipeline-pipeline-stage-execution-canceled
      - codepipeline-pipeline-stage-execution-failed
      - codepipeline-pipeline-pipeline-execution-failed
      - codepipeline-pipeline-pipeline-execution-canceled
      - codepipeline-pipeline-pipeline-execution-started
      - codepipeline-pipeline-pipeline-execution-resumed
      - codepipeline-pipeline-pipeline-execution-succeeded
      - codepipeline-pipeline-pipeline-execution-superseded
      - codepipeline-pipeline-manual-approval-failed
      - codepipeline-pipeline-manual-approval-needed
      - codepipeline-pipeline-manual-approval-succeeded
....
Notifications:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: BASIC
      EventTypeIds: !Ref NotificationEvents
      Name: !Sub ${ServiceName}_codepipeline_notifications_rule
      Resource: !Sub
        - arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PIPELINE}
        - PIPELINE: !Ref Pipeline
      Targets:
        - TargetAddress: !Ref SNSTopic
          TargetType: SNS
```
Template validation: _**Template contains errors.: Parameter 'NotificationEvents' must be one of AllowedValues**_

## 3. Expected behavior
Parameter validation should pass, since both values specified as Default are members of AllowedValues array.

Split the parameter value by comma `,` and validate each value against AllowedValues.

## 4. Suggest specific test cases

See the example above.

## 6. Category (required) 

10. Developer Tools (CodeStar, ...)
