### ISSUE TITLE
AWS::RDS::DBInstance need property to initialize master user roles

### ISSUE THREAD

**Issue by josb** [aws-cloudformation/aws-cloudformation-coverage-roadmap#634]
1. Title
AWS::RDS::DBInstance-InitialMasterUserRoles

2. Scope of request
New resource attribute
3. Expected behavior
 To use RDS IAM authentication, one has to `GRANT` the `rds_iam` role to the RDS master user. To automate this using CloudFormation, one has to write a VPC lambda for the sole purpose of logging into the RDS instance using the master password, and running
```
GRANT rds_iam TO masteruser
```
This is a lot of complexity for such a simple operation. It would be great if there was a way to assign the initial master roles in CloudFormation, so that one could do:
```
FooDB:
  Type: AWS::RDS::DBInstance
  Properties:
    ...
    InitialMasterUserRoles:
      - rds_iam
    ...
```
5. Links
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

6. Category tag
DB
