### ISSUE TITLE
AWS::Backup::BackupPlan missing "WindowsVSS"

### ISSUE THREAD

**Issue by sbrown-tecracer** [aws-cloudformation/aws-cloudformation-coverage-roadmap#637]
Scope of request -> 
https://docs.aws.amazon.com/cli/latest/reference/backup/create-backup-plan.html supports:
AdvancedBackupSettings -> BackupOptions -> WindowsVSS: enabled/disabled
Cloudformation does not.

Expected behavior -> to allow WindowsVSS switch for CloudFormation as per AWSCLI

Confirmed with AWS Support today that currently CF does NOT support this feature, therefore requesting a feature request here so that I can also follow :-)

Regards,
Sean

**Comment by kddejong** [comment]
I believe this works.  Can you validate it for me @sbrown-tecracer

```yaml
Resources:
  Backup:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: MyBackupPlan
        AdvancedBackupSettings:
          - BackupOptions:
              WindowsVSS: enabled
            ResourceType: EC2
        BackupPlanRule:
          - TargetBackupVault: Vault
            RuleName: RuleName
```
