### ISSUE TITLE
AWS::CloudFormation::StackSet does not allow setting Notifications SNS Topic ARNs for Stack Instances

### ISSUE THREAD

**Issue by piersf** [aws-cloudformation/aws-cloudformation-coverage-roadmap#656]
## 2. Scope of request 
Currently the newly released `AWS::CloudFormation::StackSet` resource does not allow setting Notifications SNS Topic ARNs for Stack Instances like the resource `AWS::CloudFormation::Stack` resource does for a stack.

In scenarios where we deploy a template to multiple accounts and multiple regions, being able to set a notifications SNS Topic ARN would allow us to have an event-driven way of receiving deployment updates/events from stack instances. This can be really powerful when we want to trigger further downstream actions(SNS -> Lambda) upon a stack instance completion.

## 3. Expected behavior

We should be able to specify a `NotificationARNs` property in `AWS::CloudFormation::StackSet` resource along with the other properties it currently supports. This  `NotificationARNs` property would accept one or more SNS Topic ARNs which the Stack Instances would inherit as well and then those would be able to publish their deployment events to the topic.

## 4. Suggest specific test cases
An example of how this would like is(see at the end):

```
Type: AWS::CloudFormation::StackSet
Properties: 
  AdministrationRoleARN: String
  AutoDeployment: 
    AutoDeployment
  Capabilities: 
    - String
  Description: String
  ExecutionRoleName: String
  OperationPreferences: 
    OperationPreferences
  Parameters: 
    - Parameter
  PermissionModel: String
  StackInstancesGroup: 
    - StackInstances
  StackSetName: String
  Tags: 
    - Tag
  TemplateBody: String
  TemplateURL: String
  NotificationARNs:
    - SnsTopicArn1
    - SnsTopicArn2
```

## 5. Helpful Links to speed up research and evaluation
[See](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns) an example of the same property used in a `AWS::CloudFormation::Stack` resource.

## 6. Category 

5. Management (CloudTrail, Config...)
8. Security (IAM, KMS...)
9. Integration (MQ, SQS, SNS,...)
10. Developer Tools (CodeStar, ...)
