### ISSUE TITLE
AWS::Cassandra::Table

### ISSUE THREAD

**Issue by codingconcepts** [aws-cloudformation/aws-cloudformation-coverage-roadmap#662]
When executing a Terraform apply using updated columns for a `AWS::Cassandra::Table`, I would expect that CloudFormation would update the affected columns.

For example:

**main.tf**
``` hcl
provider "aws" {
  region = "eu-central-1"
  version = "~> 3.0"
}

resource "aws_cloudformation_stack" "keyspaces" {
  name = "my-keyspace"

  template_body = file("./keyspace.yaml")
}
```

**keyspace.yaml**
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyKeyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: abc
  
  MyTable:
    Type: AWS::Cassandra::Table
    DependsOn: MyKeyspace
    Properties:
      KeyspaceName: abc
      TableName: my_table
      PartitionKeyColumns:
        - ColumnName: id
          ColumnType: TEXT
      BillingMode:
        Mode: ON_DEMAND
```

Instead, I receive the following error telling me that this is not currently possible:

```
Error: UPDATE_ROLLBACK_FAILED: ["The following resource(s) failed to update: [MyTable]. " "Altering column is not supported in CloudFormation currently" "Altering column is not supported in CloudFormation currently"]
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-keyspace.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-table.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack
