### ISSUE TITLE
AWS::CodeBuild::Project cannot add environment variables in CodePipeline cloudformation

### ISSUE THREAD

**Issue by skysb** [aws-cloudformation/aws-cloudformation-coverage-roadmap#668]
When creating a codepipeline via console, we have the option to add environment variables for codebuild project stages.
When trying the same via cloudformation (and a validated template) and adding the following snippet for codebuild project in codepipeline stages, I get the following error:

```
      - 
        Name: WebAppDeploy 
        Actions: 
          - 
            Name: WebAppDeployment 
            InputArtifacts: 
              -
                Name: WebAppArtifact 
            ActionTypeId: 
              Category: Build 
              Owner: AWS 
              Version: "1" 
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref AWebBuild
              EnvironmentVariables:  
                - Name: API_URL
                  Value: !Sub "#{DeployVariables.WebApiUrl}"
                  Type: PLAINTEXT
                - Name: API_VERSION
                  Value: !Sub "#{DeployVariables.AVersion}"
                  Type: PLAINTEXT
                - Name: S3_PATH
                  Value: !Sub "#{DeployVariables.S3WebsiteBucketName}"
                  Type: PLAINTEXT
            RunOrder: 1
``` 

The error I get is the following:

`Value of property Configuration must be an object with String (or simple type) properties
`--

I have tried adding a super property to environmentvariables, called environment and still in vain. I have also tried putting in a json there and template validation fails.

I believe the type "cloudformation" in the actiontypeid does allow environment variables in configuration but for some reason, when choosing codebuild, it fails to recognise environment variables.

Am I doing something wrong here or is this feature yet not supported?

Cheers
Sky

**Comment by kddejong** [comment]
@skysb I've been digging into this to triage it.

I was able to get this work after some digging.  I think the documentation could be better here but I think it does work.  According according to the examples I can find we need to have the value as a string of JSON array formatting.
https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html#action-reference-CodeBuild-example

Try this.
```yaml
Configuration:
  ProjectName: !Ref AWebBuild
  EnvironmentVariables: '[{"name":"API_URL","value":"#{DeployVariables.WebApiUrl}","type":"PLAINTEXT"},{"name":"API_VERSION","value":"#{DeployVariables.AVersion}","type":"PLAINTEXT"},{"name":"S3_PATH","value":"#{DeployVariables.S3WebsiteBucketName}","type":"PLAINTEXT"}]'
```
