### ISSUE TITLE
AWS::EC2::VPNConnection How to add PreSharedKey for the second tunnel

### ISSUE THREAD

**Issue by yongzhang** [aws-cloudformation/aws-cloudformation-coverage-roadmap#690]
Hi, I would like to add `PreSharedKey` to the second tunnel, looks like below code can only add it to tunnel 1:

```
  VPNConnectionForDev:
    Type: AWS::EC2::VPNConnection
    Properties:
      CustomerGatewayId: !Ref GustomerGatewayForDev
      StaticRoutesOnly: true
      TransitGatewayId: !Ref TransitGateway
      Type: ipsec.1
      VpnTunnelOptionsSpecifications:
      - PreSharedKey: 'xxx'
```
Please help, thanks.

**Comment by benbridts** [comment]
@yongzhang `VpnTunnelOptionsSpecifications` accepts a list, try:
```
  VPNConnectionForDev:
    Type: AWS::EC2::VPNConnection
    Properties:
      CustomerGatewayId: !Ref GustomerGatewayForDev
      StaticRoutesOnly: true
      TransitGatewayId: !Ref TransitGateway
      Type: ipsec.1
      VpnTunnelOptionsSpecifications:
      # First tunnel
      - PreSharedKey: 'xxx'
      # Second tunnel
      - PreSharedKey: 'xxx'
```

**Comment by yongzhang** [comment]
@benbridts I got this:
![image](https://user-images.githubusercontent.com/15604715/99667461-6bb71e00-2aa7-11eb-998a-ef1025158586.png)

**Comment by benbridts** [comment]
@yongzhang That's annoying. Using two PSKs or setting the `TunnelInsideCidr` explicitly for each tunnel might work around that (I don't have a VPN tunnel to test with right now).

**Comment by yongzhang** [comment]
> @yongzhang That's annoying. Using two PSKs or setting the `TunnelInsideCidr` explicitly for each tunnel might work around that (I don't have a VPN tunnel to test with right now).

You're right, yesterday I got response from aws and fixed by this:
```
      VpnTunnelOptionsSpecifications:
        # First tunnel
        - PreSharedKey: 'xxx'
           TunnelInsideCidr: 'cidr1'
        # Second tunnel
        - PreSharedKey: 'xxx'
           TunnelInsideCidr: 'cidr2'
```
