### ISSUE TITLE
ParameterGroupFamily postgres12 is not a valid parameter group family 

### ISSUE THREAD

**Issue by MatteoInfi** [aws-cloudformation/aws-cloudformation-coverage-roadmap#703]
Not sure what is wrong with this

```
  RDSParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Max connection modified
      Family: postgres12
      Parameters:
        max_connections: 200
```

when I run:

```
aws rds describe-db-engine-versions --query "DBEngineVersions[].DBParameterGroupFamily" | grep post
```

`postgres12` seems valid, even in the console

This is my db instance:

```
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgres
      Engine: postgres
      DBInstanceClass: db.t2.micro
      VPCSecurityGroups:
        - !GetAtt DatabaseSecurityGroup.GroupId
      AllocatedStorage: 5
      StorageType: gp2
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref RDSParameterGroup
```
