### ISSUE TITLE
AWS::RDS::DBCluster (enable HTTP endpoint for data API)

### ISSUE THREAD

**Issue by yvele** [aws-cloudformation/aws-cloudformation-coverage-roadmap#71]
## Title

Add an attribute to enable/disable the HTTP endpoint for an **Aurora Serverless** RDS cluster.

## Scope of request

Aurora Serverless is now production ready and is supported within CloudFormation, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-scalingconfiguration

In order to enable the Data API (that is [generally available](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/)), the HTTP endpoint must be explicitly enabled as described here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

Enabling the HTTP endpoint is possible via AWS CLI

```sh
aws rds modify-db-cluster \
    --db-cluster-identifier sample-cluster \
    --enable-http-endpoint
```

## Expected behavior

It would be nice to enable this via CloudFormation with something like

```yaml
DBCluster:
  Type: AWS::RDS::DBCluster
  Properties:
    Engine: aurora
    EngineMode: serverless
    EngineVersion: 5.6.10a
    HttpEndpointEnabled: true # <------ HERE!
```

## Other links

See also the RDS API that supports this parameter: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#modifyDBCluster-property

Related StackOverflow question: https://stackoverflow.com/questions/54931548/enable-aurora-data-api-from-cloudformation
