### ISSUE TITLE
AWS::ElasticLoadBalancingV2::TargetGroup-ProtocolVersion

### ISSUE THREAD

**Issue by intercept6** [aws-cloudformation/aws-cloudformation-coverage-roadmap#713]
## 2. Scope of request 

AWS::ElasticLoadBalancingV2::TargetGroup-ProtocolVersion can create resources via API, but not via CloudFormation.

ElasticLoadBalancingV2 `CreateTargetGroup` now supports the ProtocolVersion parameter for gRPC or HTTP2. CloudFormation needs support for this as well.

## 3. Expected behavior

In Create, it should include the `ProtocolVersion`, like the console.

## 5. Helpful Links to speed up research and evaluation

- Updated API docs at https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

**Comment by universam1** [comment]
When will this be available?

**Comment by dennisroche** [comment]
I have created a custom resource to do this in the meantime; if anyone is interested i'm happy to share it.

**Comment by OSullivanM2** [comment]
> I have created a custom resource to do this in the meantime; if anyone is interested i'm happy to share it.

If you wouldn't mind please Dennis.  Thanks

**Comment by akunszt** [comment]
@dennisroche I would be very happy to see that too. I tried to create my own but it looks like the API doesn't allow to modify the Protocol Version on an existing TargetGroup at all.

**Comment by danamajid** [comment]
https://github.com/intercept6/example-aws-cdk-custom-resource/blob/master/lib/example-aws-cdk-custom-resource.ts

**Comment by dennisroche** [comment]
> @dennisroche I would be very happy to see that too. I tried to create my own but it looks like the API doesn't allow to modify the Protocol Version on an existing TargetGroup at all.

Update requires **Replacement**, i.e. `ProtocolVersion` can only set on creation.

**Comment by dennisroche** [comment]
I have created a minimal example of HTTP2 Target Group custom resource https://gist.github.com/dennisroche/287915ca6a0874157d71b0903ec3999b

**Comment by akunszt** [comment]
Luckily it turned out - with the help of the AWS Support - that it's only a documentation issue. You can use the `ProtocolVersion` in the CloudFormation template. For example this worked for me:
```yaml
---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /AWS.ALB/healthcheck
      HealthCheckPort: '8443'
      HealthCheckProtocol: HTTP
      ProtocolVersion: HTTP2
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      Matcher:
        HttpCode: 200-299
      Port: 8443
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: vpc-XXX
```
