### ISSUE TITLE
AWS::CloudFormation - Dynamic Reference - reslove:ssm - Latest Version

### ISSUE THREAD

**Issue by jmacgowa-ks** [aws-cloudformation/aws-cloudformation-coverage-roadmap#716]
## 1. AWS::CloudFormation - General Capability: Dynamic Reference - reslove:ssm - Latest Version

This is a general feature/capability request, and not limited to any specific resource type.

## 2. Scope of request 

The resolve:ssm and resolve:ssm-seccure dynamic references supported within CloudFormation templates should allow the option of a "latest" version. Currently, a hard-coded version number is required which then breaks template re-use, as each environment will have differing versions.

### Samples: 
{{resolve:ssm:parametername:2}} = version 2
{{resolve:ssm:parametername}} = stack fails
{{resolve:ssm-secure:parametername}} = stack fails

### Samples: 
{{resolve:ssm:parametername}} = latest version
{{resolve:ssm-secure:parametername}} = latest version

**Other possible solutions:**
{{resolve:ssm:parametername:}}
{{resolve:ssm:parametername:0}}
{{resolve:ssm:parametername:-1}}
{{resolve:ssm:parametername:latest}}

## 4. Suggest specific test cases

Create a template that contains a dynamic reference in it as below. Leave out the version number.
```
Resources:
  WebService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      LaunchType: FARGATE
      PlatformVersion: '{{resolve:ssm:/ecs/fargatePlatformVersion}}'
...
```

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html

## 6. Category
Management & Governance - CloudFormation - Dynamic References
Management & Governance - Systems Manager

## 7. Any additional context (optional)

As a workaround for this problem, we have been using a CloudFormation Macro to look-up the latest version and transform all dynamic references. This solution has been problematic and breaks other features such as change sets with nested stacks.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/664
