### ISSUE TITLE
AWS::RDS::DBInstance (add Storage Auto Scaling)

### ISSUE THREAD

**Issue by davecashin** [aws-cloudformation/aws-cloudformation-coverage-roadmap#72]
Title -> Amazon RDS now supports Storage Auto Scaling, it would be useful for many customers to have support for this feature within CloudFormation
Scope of request -> Add abilty to enable storage auto scaling on creating new RDS resources.
Expected behavior -> See relevant documentation:
Test case recommendation (optional) ->
Links to existing API doc (optional) ->  https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.Autoscaling
Category tag (optional) -> Databases
Any additional context (optional) -> https://aws.amazon.com/about-aws/whats-new/2019/06/rds-storage-auto-scaling/

**Comment by jalvarezferr** [comment]
+1

**Comment by jvsell** [comment]
Any news about this feature?
+1

**Comment by luiseduardocolon** [comment]
going to try to get an update this week - stay tuned

**Comment by lwoggardner** [comment]
Release notes say it is already done - Dec 20 Added support for MaxAllocatedStorage property.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html.

**Comment by ohadbenita** [comment]
> Release notes say it is already done - Dec 20 Added support for MaxAllocatedStorage property.
> [docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

Someone gave it a try ?

**Comment by gregory-viale-cbp** [comment]
Once the value MaxAllocatedStorage is set : the function Enable storage autoscaling is activated

**Comment by Dandandan** [comment]
This doesn't seem to work yet. Setting MaxAllocatedStorage to 1024 doesn't create a DB with auto scaling enabled for me using postgres.

**Comment by Dandandan** [comment]
The cloudformation spec looks like this:

```
  DB:
    DependsOn:
      - DBSecurityGroup
      - DBPassword
      - DBSubnetGroup
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
        - Ref: DBSecurityGroup
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref DBSubnetGroup
      AllocatedStorage: "10"
      MaxAllocatedStorage: 1024
      Engine: postgres
      MasterUsername: root
      MasterUserPassword: !GetAtt DBPassword.Secret
      SourceRegion: !Ref "AWS::Region"
      StorageEncrypted: true
    DeletionPolicy: Snapshot
```
