### ISSUE TITLE
AWS::Lambda::Function-ImageConfig

### ISSUE THREAD

**Issue by Hazelfire** [aws-cloudformation/aws-cloudformation-coverage-roadmap#722]
AWS::Lambda::Function currently has support for container runtimes! However, it is currently impossible to configure them using cloudformation due to lacking appropriate parameters such as ImageConfig and ImageUri.

Would be expecting something like this to work:
```yaml
Resources:
  MyFunc: 
    Type: AWS::Lambda::Function
    Properties:
      Runtime: provided
      ImageConfig:
        EntryPoint: /bin/my-exe
        WorkingDirectory: /
      Code:
        ImageUri: my-user-id.dkr.ecr.us-east-1.amazonaws.com/my-repo
```
Should create the resource as the API and CLI allows for. I don't think there is anything particularly unusual about Delete or Update either.

Useful links:
 - [create-function in AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html)
 - [AWS Lambda Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html)

Category: Compute
