### ISSUE TITLE
AWS::S3::Object

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#76]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::S3::Object
2. Scope of request -> Add the ability to manage objects, like configuration, within CloudFormation templates
3. Expected behavior -> I should be able to store object contents in JSON, YAML, text, or binary. I should be able to provide JSON and YAML objects as native CloudFormation (either JSON or YAML, and converting to my desired output format). Binary given as Base64. I should also be able to copy an object from another bucket.
4. I should be able to write a YAML-formatted object from a JSON-formatted template.
5. Links to existing API doc -> N/A
6. Category tag -> Compute
7. Additional context:
This would allow the ability for configuration files to get written with references to a template, that can then get picked up at runtime by other users.

The ability to copy from another bucket would allow SAM to allow users to specify local paths and upload the files to a temporary bucket (along with code, etc.), and then CloudFormation could copy from there.

Example:
```yaml
MyConfigObject:
  Type: AWS::S3::Object
  Properties:
    Bucket: !Ref TheBucket
    Key: /my/object/key
    Value:
      Json:
        Key: Value
        MyRef: !Ref SomeOtherResource
```
would write the following content:
```javascript
{"Key":"Value","MyRef":"arn:aws:..."}
```

```javascript
{
  "MyConfigObject": {
    "Type": "AWS::S3::Object",
    "Properties": {
      "Bucket": {"Ref": "TheBucket"},
      "Key": "/my/object/key",
      "Value": {
        "Yaml": {
          "Key": "Value",
          "MyRef": {"Ref": "SomeOtherResource"}
        }
      }
    }
  }
}
```
would write the following content:
```yaml
Key: Value
MyRef: arn:aws:...
```
