### ISSUE TITLE
Fn::JsonString

### ISSUE THREAD

**Issue by Sviat** [aws-cloudformation/aws-cloudformation-coverage-roadmap#78]
## 1. Title
Fn::JsonString

## 2. Scope of request 
JSON CloudFormation Templates.

Whenever a resource has property that requires content as JSON String, we all either write this Fn::Join's with "\n" and other workarounds, or convert JSON to String by external tool.

This lowers readability of code (Infrastructure is a Code!) to zero, and highers maintenance costs.
Example: 
## 3. Expected behavior
Instead of trying to construct string out of JSON key-values and Fn::Ref's / Fn::GetAtt's, should be possible to assign property JSON object and hope CloudFormation will handle the rest.

Example:

`    "Resources": {
        "Dashboard": {
            "Type" : "AWS::CloudWatch::Dashboard",
            "Properties" : {
                "DashboardName" : "Lorem Ipsum 42",
                "DashboardBody" : { "Fn::JsonString": { 
  "Key1": "Value",
  "Key2": { "Fn::Ref": "SomeId" },
  "Key3": { ... }
}
}` 

## 4. Suggest specific test cases
See 3.

## 6. Category
11. Other (IoT, Migration, Budgets...) -  Intrinsic Functions

**Comment by jk2l** [comment]
+1 on this.

Use case for me, rather than try to write and escape a string in json format. i will prefer I can let a function automate it

```
  # FROM 
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${SecretNamespace}"
      Description: "This is a shared secret."
      SecretString:
        Fn::JsonString:
          username: "test-user"
      KmsKeyId: !Ref SecretKmsKey

 # TO
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${SecretNamespace}"
      Description: "This is a shared secret."
      SecretString:  "{\"username\":\"test-user\"}"
      KmsKeyId: !Ref SecretKmsKey
```

I lost count how many time i have some copy and paste issue or some syntax issue that break the JSON validation. having a function to automate it will be a great feature

**Comment by benkehoe** [comment]
Not to take away from this very valid request, but you can accomplish this a little bit today, using YAML's [multiline syntax](https://yaml-multiline.info/). For example:
```yaml
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${SecretNamespace}"
      Description: "This is a shared secret."
      SecretString: !Sub >-
        {"username": "${UserName}"}
      KmsKeyId: !Ref SecretKmsKey
```
