### ISSUE TITLE
AWS::Route53::HostedZone::Id - Better behavior if not selected in Parameters:

### ISSUE THREAD

**Issue by docktermj** [aws-cloudformation/aws-cloudformation-coverage-roadmap#792]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::Service::Resource-Attribute-Existing Attribute
2. Scope of request -> AWS::Service::ResourceType::TheResource-ExistingAttribute supports A and B today, but not new C feature.
3. Expected behavior -> In Create, it should include this and this, like the console.  Also include tag creation, like the API allows.
4. Test case recommendation (optional) -> it should help me do X given existing Y (if applicable); it should/shouldn't change Z.
5. Links to existing API doc (optional) -> Updated API docs at https://example.com/api-new.html
6. Category tag (optional) -> Compute
7. Any additional context (optional)

Detailed Instructions to create a new issue here: (delete this text before you save your issue, to keep them as short as possible :) ). 

#### AWS::Route53::HostedZone::Id

We are hoping that the title makes it easy for others to scan it quickly in kanban board or issue list. 

## 2. Scope of request 

If a CloudFormation template has this Parameter:

```yaml
Parameters:
  Route53HostedZoneId:
    Default: ''
    Type: AWS::Route53::HostedZone::Id
```

and the User does not select a Hosted Zone or if there is no Hosted Zone, there should be a way for the Cloudformation to detect this and use `Condition` to avoid using the Hosted Zone.

Specifically, if a user chooses a Hosted Zone, then the Cloudformation can create an HTTPS-based solution.  If a Hosted Zone is not chosen, the Cloudformation can create an HTTP-based solution.   For instance:

```yaml
  ListenerSwaggerHttps:
    Condition: IfRoute53HostedZoneId
    Properties:
      Certificates:
        - CertificateArn: !GetAtt LambdaRunnerFindDomainName.CertificateArn
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroupSwagger
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerPublic
      Port: 443
      Protocol: HTTPS
    Type: AWS::ElasticLoadBalancingV2::Listener
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

4.  Networking & Content (VPC, Route53, API GW,...)
