### ISSUE TITLE
AWS::ServiceCatalog::CloudFormationProvisionedProduct-GetAtt Values from Product Stack

### ISSUE THREAD

**Issue by Ricapar** [aws-cloudformation/aws-cloudformation-coverage-roadmap#81]
## 2. Scope of request 
The `AWS::ServiceCatalog::CloudFormationProvisionedProduct` resource has two return values, the `Ref` (product ID) and a `GetAtt` for `CloudformationStackArn` and `RecordId`.

What seems to be missing is the ability to get the values of the Outputs of the CloudFormation stack that it created for you.

## 3. Expected behavior

I believe this would be much more useful if it behaved like `GetAtt <stack>.Outputs.OutputName` does on [AWS::CloudFormation::Stack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html).

## 4. Suggest specific test cases

I would love to do this:

```
ResourceA:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct 
    Properties: 
        ...stuff....

ResourceB:
    Type: AWS::OtherService::OtherResource
    Properties:
        SomeProperty: !GetAtt ResourceA.Outputs.SomeOutputValue
```

## 5. Helpful Links to speed up research and evaluation

Documentation for AWS::CloudFormation::Stack:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

Documentation for AWS::ServiceCatalog::CloudFormationProvisionedProduct:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-cloudformationprovisionedproduct.html

## 6. Category

5. Management (CloudFormation, Service Catalog)
