### ISSUE TITLE
AWS::SSM::Parameter-Type-SecureString

### ISSUE THREAD

**Issue by melbit-benlucas** [aws-cloudformation/aws-cloudformation-coverage-roadmap#82]
## 2. Scope of request 

When creating a new SSM Parameter resource you can create using the String and StringList Type however not SecureString.

This is currently possible with additional lambda functions within the template however it will make for easier to follow templates for both parameter creation and dynamic linking to ssm parameters.

We use SSM Parameters for variables, including sensitive data, so the ability to continue utilising these without manual creation before a stack deployment is desired.

Sample: 
## 3. Expected behaviour

As part of the Console or API, we can create a new SecureString Parameter. It's expected that CloudFormation should also include this functionality.

## 4. Suggest specific test cases

Common use case: Creating a securestring parameter during stack creation from inputted parameters. These parameters can then be dynamically referenced throughout the stack.

Test case recommendation: Ability to create a securestring value and reference it from the same stack.

## 5. Helpful Links to speed up research and evaluation

Reference Doc detailing the feature doesn't yet exist. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html

## 6. Category

Management - Systems Manager

## 7. Any additional context (optional)

We currently get around this using 3 ways:

1. Manual SecureString Parameter creation pre stack create.
2. Addition lambda function to create the secure parameter (Add complexity to the template).
3. Create and use Secrets Manager. (This works well however at scale the cost of Secrets Manager become prohibitive)

**Comment by benkehoe** [comment]
How do you expect to use this without disclosing the value of the parameter in the template?

**Comment by melbit-benlucas** [comment]
Typically we’d use NoEcho on any sensitive parameters plus our deployment tooling would pass the values from it’s own secure store during stack creation which shouldn’t  expose the value at any point of creation.

**Comment by trav-c** [comment]
> How do you expect to use this without disclosing the value of the parameter in the template?
Another use case is just to be able to create the parameter as a placeholder with an empty value so that it can be easily manually populated with the security sensitive details later, but it's existence can be referenced elsewhere in the stack immediately.  We do this in our existing stack using a custom resource

**Comment by ikben** [comment]
Additionally, our Custom Resources supports generation a random value when the Parameter is created. This could be something that CloudFormation does itself, or CloudFormation could call [secretsmanager get-random-password](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetRandomPassword.html) or [kms generate-random](https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateRandom.html) behind the scenes.

**Comment by rajanarkenbout** [comment]
Would like to be able to dynamically pull values from SSM for example with {environment} or {version} where environment for example is, test, staging, production and version is, 1, 2, 3, etc..

 "{{resolve:ssm-secure:/{environment}/password:{version}}}"

**Comment by cmarshall10450** [comment]
Has anyone been able to use the ssm dynamic referencing with the Join or Sub intrinsic functions? I'm trying to write a file in the CloudFormation::Init metadata of an EC2 instance with a username and password for a service but it writes out the reference syntax to the file instead of resolving.

**Comment by jospas** [comment]
> > How do you expect to use this without disclosing the value of the parameter in the template?
> 
> Another use case is just to be able to create the parameter as a placeholder with an empty value so that it can be easily manually populated with the security sensitive details later, but it's existence can be referenced elsewhere in the stack immediately. We do this in our existing stack using a custom resource

This is a common ask, create a SecureString ParameterStore parameter with a dummy value and have another team update the value for various environments. Can we get support for this feature please?

**Comment by KasperFranz** [comment]
Any update on this?
For us to properly utilise SSM Parameter store with CloudFormation we need to be able to create Secure parameters

**Comment by martavoi** [comment]
Wow, such a required feature and still no support...

**Comment by unfor19** [comment]
If you're ok with using a custom resource, then this is a great solution - https://github.com/glassechidna/ssmcfn, I'm using it for creating SecureString parameters with a dummy initial value "empty".

Deploy this CloudFormation template (per region if you're working across regions):

<details>

<summary>

[cfn.yml](https://github.com/glassechidna/ssmcfn/blob/master/cfn.yml) - Expand/Collapse

</summary>

I commented out the support for `UPDATE`, so it only works upon CREATE+DELETE and does not attempt to update the value. I also updated the runtime from `node4.3` to node `12.x` (latest version that supports ZipFile)

```yaml
# Source: https://github.com/glassechidna/ssmcfn/blob/master/cfn.yml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: nodejs12.x
      Timeout: 300
      Code:
        ZipFile: >
          var response = require('cfn-response');
          var aws = require('aws-sdk');

          exports.handler = function(event, context) {
              console.log(event);
              
              var ssm = new aws.SSM();
              var props = event.ResourceProperties;

              var splitStackArn = event.StackId.split(':');
              var region = splitStackArn[3];
              var accountId = splitStackArn[4];

              var stackName = splitStackArn[5].split("/")[1];
              var paramName = props.Name || "cfn-" + stackName + "-" + event.LogicalResourceId; // TODO: add rand on end?
              var paramArn = "arn:aws:ssm:" + region + ":" + accountId + ":parameter/" + paramName;

              var cb = function(err, resp) {
                  var cfnRespData = { Arn: paramArn, Name: paramName };
                  if (err) {
                      console.log(err);
                      response.send(event, context, response.FAILED, cfnRespData, paramArn);            
                  } else {
                      console.log(resp);
                      response.send(event, context, response.SUCCESS, cfnRespData, paramArn);            
                  }
              };

              if (event.RequestType == "Create") {
                  var params = {
                      Name: paramName,
                      Type: "SecureString", // Hardcoded SecureString instead of using props.Type
                      Value: props.Value,
                      KeyId: props.KeyId,
                      Overwrite: false
                  };

                  if (props.Description) params.Description = props.Description;
                  if (props.KeyId) params.KeyId = props.KeyId;
                  
                  ssm.putParameter(params, cb);
              } 
              /*
              Skipping update, we only want to create it
              else if (event.RequestType == "Update") {
                  var params = {
                      Name: paramName,
                      Type: props.Type,
                      Value: props.Value,
                      KeyId: props.KeyId,
                      Overwrite: true
                  };

                  if (props.Description) params.Description = props.Description;
                  if (props.KeyId) params.KeyId = props.KeyId;

                  ssm.putParameter(params, cb);
              } 
              */
              else if (event.RequestType == "Delete") {
                  ssm.deleteParameter({ Name: paramName }, cb);
              }
          };
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - kms:Encrypt
                Resource: "*"
Outputs:
  Lambda:
    Description: Cfn polyfill for SSM parameter store
    Value: !GetAtt Lambda.Arn
    Export:
      Name: CfnParamStore
  HelperRole:
    Description: IAM Role
    Value: !GetAtt Role.Arn
    Export:
      Name: SSMHelperRole
```

</details>

<details>

<summary>

[example.yaml](https://github.com/glassechidna/ssmcfn/blob/master/example.yml) - Expand/Collapse

</summary>

I added the `Name` property and some comments. Also, there's no need to define the `Type` since the default type in the Lambda is `SecureString`.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecureParam:
    Type: Custom::CfnParamStore
    Properties:
      Name: /my-app/development/my-secret
      ServiceToken: !ImportValue CfnParamStore # Required to use the Helper
      Value: empty # Initial dummy value
Outputs:
  ParamArn:
    Description: Arn of param in SSM param store
    Value: !GetAtt SecureParam.Arn
```

</details>

**Comment by ckabalan** [comment]
Any update on this? Our organization has use cases as described above. Our workflow is like what @jospas describes. For new deployments which require secrets we deploy the app with a dummy value `REPLACE_WITH_SECRET_STRING` and as part of our deployment process manually replace that value with the actual secret content.

Any fear of invalid/insecure usage has already been accepted because `AWS::SecretsManager::Secret` already has a `SecretString` field.

It would be nice to get this prioritized.

**Comment by dtphuc** [comment]
Any news update on this feature?
We’re waiting for a while

**Comment by mayormaier** [comment]
Want to put a bump on this- not sure if it will be in development, but definitely a good idea.

**Comment by cbaker** [comment]
+1

**Comment by tazatwell** [comment]
Hi, for any newcomers to this thread I wrote a workaround for creating/updating/deleting SecureString Parameters at https://github.com/tazatwell/ssm-securestring-cfn-macro. It follows the suggested workaround solution, a Lambda-backed CloudFormation macro.

**Comment by beck3905** [comment]
I'll add another use case to this thread.  Our organization has a requirement that all configuration be stored encrypted at rest.  This includes things like ARNs and URLs, etc. that our applications may need to use.  Our templates create resources and then save the ARNs, etc to SSM parameters for our applications to read as configuration.  But our requirements dictate that those SSM parameters must be SecureString.  So we have a need to create new SecureString parameters directly in our template and put values from other resources created by the stack.

**Comment by Lu-dorado** [comment]
Any news about this? It would be a great news to be discovered art re:Invent!

**Comment by pepitoenpeligro** [comment]
Hi team, any news about this? It's a tricky but important use case :)

**Comment by esuter-rms** [comment]
Just adding another "vote" on this: like others have mentioned elsewhere in the thread, all my organization needs is to be able to create placeholder secure string parameters when deploying with CDK, which will be updated later via another process external to our deployment pipeline.

Before anyone suggests using SecretsManager: it's overkill for the the majority of the secrets we need to store, most do not need frequent rotation, and we overwrite the auto-generated strings 99% of the time anyway with something else. SecretsManager isn't exactly cheap either.

I'm honestly surprised that there's been no visible effort to implement this use case for almost 5 years.

**Comment by djravine** [comment]
+1

**Comment by MichaelDavisTSN** [comment]
We need this to support Instance Scheduler on AWS, so that SecureString can be created with the published templates. Our company policy requires encrypted parameters. Thanks!

**Comment by valeriosalvucci** [comment]
+1

**Comment by ThomasVaccarini** [comment]
Waiting for this...

**Comment by lechgajewski** [comment]
Upvoting this request as well 👍 

Feature like this would be extremely useful when specifying the `Parameter` for the CloudFormation template, e.g.:

```yaml
Parameters:
  SomeSecureParam:
    Type: AWS::SSM::Parameter::Value<SecureString>
    Default: /path/to/some/secure/param
```

Unfortunately the support for the dynamic SSM Parameter resolution aka. ``{{{{resolve:ssm-secure:/path/to/some/secure/param}}`` is so limited that it's not really a viable alternative 😞

**Comment by frankieshum** [comment]
Feels like there's no interest in implementing this feature because storing secure SSM parameters isn't profitable, whereas storing secrets in Secrets Manager generates $0.40 per month...

![Untitled](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/51829780/0f5d610d-a2a0-4c3d-8e36-e2886e9202da)

**Comment by bcoddens** [comment]
Can this be given priority ? This is blocking us to create a security baseline in our Organization.

**Comment by CGarces** [comment]
> Can this be given priority ? This is blocking us to create a security baseline in our Organization.

I think that  https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/82#issuecomment-2120472605  has the key of when will be implemented.

**Comment by bleeding-panda** [comment]
Pinging the team again

**Comment by badfun** [comment]
On the one hand AWS preaches "infrastructure as code", on the other they block us from being able to implement it. CF won't create secure string parameters, and resource share won't share them after you've done it all manually. Works just fine in the console, but actually doing IaC is not supported.

**Comment by airosa** [comment]
Couple of interesting things i noticed about this issue:
- it is currently 9th oldest open issue in this repo
- It was opened 1,891 days ago that's 5.1 years
- it still has not been resolved

**Comment by jpSimkins** [comment]
coming to the end of 2024 and this is still not added. Hoping for 2025!

**Comment by cilki** [comment]
Who's willing to get hired at AWS, push this one through, then quit?

**Comment by dtphuc** [comment]
Don’t know why the critical feature is very slow response from AWS

Thanks & Regards.
Phuc Dang

**Comment by chdanielmueller** [comment]
Feedback from my contact at AWS:
> I asked our technical team internally and was told that this feature was not on our roadmap.

I have now been added to a _Product Feature Request_. Seems like GitHub Issues here do not provide a signal to AWS that we would like something new. So please write to your contact at AWS to make sure they know about us.

**Comment by p10tyr** [comment]
Since new SDK's and Runtimes have been created since the OG issue. I'd like to share the updated Node20 async and sdk3 commonJS. Also, I hanged it to always respond as success (and log out error only) because if the stack hangs in create or delete ... you have to wait amazon years before you can retry.

```javascript
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: nodejs20.x
      Timeout: 300
      Code:
        ZipFile: >
         var response = require('cfn-response');
         const { SSMClient, PutParameterCommand, DeleteParameterCommand } = require("@aws-sdk/client-ssm");
         
         exports.handler = async function(event, context) {
           console.log(event);
           
           var ssmClient = new SSMClient();
           var props = event.ResourceProperties;
         
           var splitStackArn = event.StackId.split(':');
           var region = splitStackArn[3];
           var accountId = splitStackArn[4];
         
           var stackName = splitStackArn[5].split("/")[1];
           var paramName = props.Name || "cfn-" + stackName + "-" + event.LogicalResourceId; // TODO: add rand on end?
           var paramArn = "arn:aws:ssm:" + region + ":" + accountId + ":parameter/" + paramName;
         
           var cfnRespData = { Arn: paramArn, Name: paramName };
         
           if (event.RequestType == "Create") {
               var params = {
                   Name: paramName,
                   Type: "SecureString", // Hardcoded SecureString instead of using props.Type
                   Value: props.Value,
                   KeyId: props.KeyId,
                   Overwrite: false
               };
         
               if (props.Description) params.Description = props.Description;
               if (props.KeyId) params.KeyId = props.KeyId;
               
               try  {
                 const createCommand = new PutParameterCommand(params);
                 const responsePut = await ssmClient.send(createCommand);
               }
               catch (err){}
           } 
           else if (event.RequestType == "Delete") {
             try{
                 const deleteCommand = new DeleteParameterCommand({ Name: paramName });
                 const responseDelete = await ssmClient.send(deleteCommand);
             }
             catch(err){}
           }
         
           //return success always to prevent stack from freezing up
           await response.send(event, context, response.SUCCESS, cfnRespData, paramArn);
         };

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - kms:Encrypt
                Resource: "*"
Outputs:
  Lambda:
    Description: Cfn polyfill for SSM parameter store
    Value: !GetAtt Lambda.Arn
    Export:
      Name: CfnParamStore
  HelperRole:
    Description: IAM Role
    Value: !GetAtt Role.Arn
    Export:
      Name: SSMHelperRole

# https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/82#issuecomment-817331138
# Source: https://github.com/glassechidna/ssmcfn/blob/master/cfn.yml
```

You can set the service timeout on your stack creating these default secreters

```yaml
  SomeOptionsApiKey:
    Type: Custom::CfnParamStore
    Properties:
      ServiceTimeout: 60 <----- Seconds to wait before failing
      Name: "/a-lambda-adapter/${Environment}/Api/Key"
      ServiceToken: !ImportValue CfnParamStore # Required to use the Helper
      Value: empty
```

**Comment by chdanielmueller** [comment]
We have created a custom CloudFormation Extension which supports creating secrets in the SSM Parameter Store.
There are parameters if you want to set a defined password or generate one.
You can also use the password in places where "{{resolve:ssm-secure}}" is not supported.
The installation needs some CLI-Tools but everything is described within the `README.md`.

You can find it here:
https://github.com/Surnet/cloudformation-systemsmanager-parameterstore-secret 

We would like to hear your feedback.
If demand is high enough I could try to get it published as a public extension.

### Generated Passwords

```yaml
Resources:
  MyDatabaseSecret:
    Type: Surnet::ParameterStore::Secret
    Properties:
      Name: /prod/db/password
      Description: "Production database password"
      PasswordOptions:
        Length: 24
        IncludeNumbers: true
        IncludeSymbols: true
        Serial: 1
      Tags:
        - Key: Environment
          Value: Production
        - Key: Application
          Value: MyApp

Outputs:
  DatabasePassword:
    Value: !GetAtt MyDatabaseSecret.Password
    Description: "The generated database password"
```

### User-defined Passwords

```yaml
Resources:
  MyDatabaseSecret:
    Type: Surnet::ParameterStore::Secret
    Properties:
      Name: /prod/db/password
      Description: "Production database password"
      PasswordInput: "MySuperSecretPassword"
      Tags:
        - Key: Environment
          Value: Production
        - Key: Application
          Value: MyApp

Outputs:
  DatabasePassword:
    Value: !GetAtt MyDatabaseSecret.Password
    Description: "The generated database password"
```
