### ISSUE TITLE
AWS::CodeDeployBlueGreen Transform (CodeDeploy)

### ISSUE THREAD

**Issue by jmurzy** [aws-cloudformation/aws-cloudformation-coverage-roadmap#821]
Following the instructions [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html). I'm getting the following error when trying to update the task definition with a new image.

```
Error: Failed to create ChangeSet cdk-deploy-change-set on MyStack: FAILED, Transform AWS::CodeDeployBlueGreen failed with: Failed to transform template. Failed to parse the "Hooks" section for the provided template. Please ensure the AWS::CodeDeploy::BlueGreen Hook matches the expected schema.
```

Here's the hook
```yml
Transform: AWS::CodeDeployBlueGreen
Hooks:
  CodeDeployBlueGreenHook:
    Type: AWS::CodeDeploy::BlueGreen
    Properties:
      ServiceRole: MyRole
      Applications:
        - Target:
            Type: AWS::ECS::Service
            LogicalID: ECSService
          ECSAttributes:
            TaskDefinitions:
              - TaskDefBlue
              - TaskDefGreen
            TaskSets:
              - TaskSetBlue
              - TaskSetGreen
            TrafficRouting:
              ProdTrafficRoute:
                Type: AWS::ElasticLoadBalancingV2::Listener
                LogicalID: LoadBalancer
              TestTrafficRoute:
                Type: AWS::ElasticLoadBalancingV2::Listener
                LogicalID: LoadBalancerTest
              TargetGroups:
                - BlueTg
                - GreenTg
      TrafficRoutingConfig:
        Type: TimeBasedCanary
        TimeBasedCanary:
          StepPercentage: 20
          BakeTimeMins: 15
      AdditionalOptions:
        TerminationWaitTimeInMinutes: 30
```

Can your team maybe open source the CodeDeployBlueGreen transform so we can do our own debugging? Otherwise, we'll probably need a little more than "Please ensure the AWS::CodeDeploy::BlueGreen Hook matches the expected schema"—especially given this is a CDK generated schema and it passes all other checks.

Thanks!

cc @clareliguori
