### ISSUE TITLE
AWS::SSO::Assignment - TargetId - PermissionSetArn - PrincipalId

### ISSUE THREAD

**Issue by Geordam** [aws-cloudformation/aws-cloudformation-coverage-roadmap#828]
2. Scope of request -> AWS::SSO::Assignment - TargetId - PermissionSetArn - PrincipalId
This section allows only one ID per property. We would like to be able to put lists of IDs/ARNs

3. Expected behavior -> Instead of putting only 1 ID per property we need to put lists.
Instead of :
```
Type: AWS::SSO::Assignment
Properties: 
  InstanceArn: InstanceArn1
  PermissionSetArn: PermissionSetArn1,PermissionSetArn2
  PrincipalId: PrincipalId1
  PrincipalType: group
  TargetId: ACCOUNT1
  TargetType: AWS_ACCOUNT

Type: AWS::SSO::Assignment
Properties: 
  InstanceArn: InstanceArn1
  PermissionSetArn: PermissionSetArn1,PermissionSetArn2
  PrincipalId: PrincipalId1
  PrincipalType: group
  TargetId: ACCOUNT2
  TargetType: AWS_ACCOUNT
```
We want :
```
Type: AWS::SSO::Assignment
Properties: 
  InstanceArn: InstanceArn1
  PermissionSetArn: PermissionSetArn1,PermissionSetArn2
  PrincipalId: PrincipalId1
  PrincipalType: group
  TargetId: ACCOUNT1,ACCOUNT2,...
  TargetType: AWS_ACCOUNT
```

5. Links to existing API doc -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-assignment.html
6. Category tag -> Assignment
7. Any additional context 
There are some workaround on internet, for example : https://ig.nore.me/2020/10/fixing-aws-ssos-cloudformation/

**Comment by benkehoe** [comment]
This request is more properly a request for an _assignment group,_ and is better directed to the AWS SSO team; it has already been communicated to them more than once. In the meantime, there are two 3rd party tools you can use to accomplish this:
* [`aws-sso-util`](https://github.com/benkehoe/aws-sso-util/blob/master/docs/cloudformation.md) provides a [CloudFormation Macro](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html) that allows you to specify multiple principals, permission sets, accounts, and even OUs as targets. The macro translates your template to straight CloudFormation, so the assignments are still directly managed by CloudFormation (I find this desirable, which is why I wrote it 🙂)
* [OrgFormation](https://github.com/org-formation/aws-resource-providers/tree/master/sso/assignment-group) provides a [CloudFormation resource provider](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-types.html) that accomplishes the same thing; the resource provider is responsible for managing all of the assignments itself.

**Comment by Geordam** [comment]
@benkehoe Thank you for the comment.
I gave a try to the macro workaround but I am a bit lost on how the template should look.
in your documentation I believe it shows only a part :
```
MyAssignmentGroup:
  Type: AWSSSOUtil::SSO::AssignmentGroup
  Properties:
    Name: MyAssignmentGroup # As documentation
    InstanceArn: arn:aws:sso:::instance/ssoins-d9e7477013d8e62a
    Principal:
    - Type: USER
      Id: c843295c-d41f-4f23-9832-1521dbaf36f7
    - Type: GROUP
      Id:
      - 6c1645fc-37b5-40ba-8c3d-5216b9055505
      - 67d02fc7-ef1e-463f-b572-ba9b2fe710ba

    PermissionSet:
    - arn:aws:sso:::permissionSet/ssoins-69e2ecd0b249f0cd/ps-45b2cb9e8a6aee12
    - ssoins-69e2ecd0b249f0cd/ps-04a493b762a3fef9
    - ps-b5b9375180ceaaac
    - !GetAtt SomePermissionSetResource.PermissionSetArn

    Target:
    - Type: AWS_OU
      Id: ou-7w1i-suzvrczk
    - Type: AWS_OU
      Recursive: True
      Id: ou-qlmf-1j9r4iq9
    - Type: AWS_ACCOUNT
      Id:
      - 123456789012
      - 174652129131
```
But I am not sure to understand what else is required in it.
I have put this for example : 
```
AWSTemplateFormatVersion: "2010-09-09"
Description: "Team permission set and Assignment"

Transform: "AWS-SSO-Util-2020-11-08"

Parameters:
  InstanceArn:
    Type: String
    Default: 'arn:aws:sso:::instance/ssoins-1234567890'

Resources:
  WaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
  PermissionSet:
      Type: AWS::SSO::PermissionSet
      Properties:
        InstanceArn: !Sub ${InstanceArn}
        Name: 'sre-access'
        Description: 'Team permission set and Assignment'
        SessionDuration: 'PT8H'
        ManagedPolicies:
          - 'arn:aws:iam::aws:policy/AdministratorAccess'

  MyAssignmentGroup:
    Type: AWSSSOUtil::SSO::AssignmentGroup
    Properties:
      Name: MyAssignmentGroup # As documentation
      InstanceArn: !Sub ${InstanceArn}
      Principal:
      - Type: GROUP
        Id:
        - 123456789-44e-50-e2-77836
      PermissionSet:
      - !GetAtt PermissionSet.PermissionSetArn
      Target:
      - Type: AWS_ACCOUNT
        Id:
        - 123456789
        - 987654321
```

I guess I do something wrong as it shows that  _Type: AWSSSOUtil::SSO::AssignmentGroup_ is not supported

Would you mind providing some guidance please ?
