### ISSUE TITLE
Drift detection can't detect inline policies added to an IAM Role.

### ISSUE THREAD

**Issue by tstibbs** [aws-cloudformation/aws-cloudformation-coverage-roadmap#936]
### Name of the resource

AWS::IAM::Role

### Resource Name

AWS::IAM::Role

### Issue Description

If an inline policy is added to an IAM role, drift detection should pick that up as drift (because the permissions of the role have materially changed).

### Expected Behavior

Drift detection should mark the resource as 'MODIFIED' and thus the stack as 'DRIFTED'.

### Observed Behavior

Drift detection marks the resource and stack as 'IN_SYNC'.

### Test Cases

1. Deploy a stack with the following template: 
    ```
    Resources:
      testRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Statement:
              - Action: sts:AssumeRole
                Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
            Version: "2012-10-17"
    ```
1. Manually add an inline policy to the role in the IAM console
1. Run drift detect
1. Note that drift detection doesn't pick up the added policy
